import '@fontsource-variable/archivo'
import '@fontsource-variable/source-serif-4/opsz.css'
import '@fontsource-variable/manrope'
import './style.css'
import './gallery.css'
import { groups, services, projects, articles, field, art } from './content.js'
import { icon } from './icons.js'
import { mountNetwork } from './network.js'
import { galleryPages } from './gallery.js'

const q = new URLSearchParams(location.search)
const requested = q.get('pagina') || 'inicio'
const page = requested === 'quienes-somos' ? 'nosotros' : requested
const id = q.get('id')
const main = document.getElementById('content')
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const link = (p, record) => `/?pagina=${p}${record ? `&id=${encodeURIComponent(record)}` : ''}`
const nav = [['inicio','Inicio'],['nosotros','Quiénes somos'],['servicios','Servicios'],['proyectos','Proyectos'],['articulos','Artículos'],['contacto','Contacto']]
const active = {servicio:'servicios',proyecto:'proyectos',articulo:'articulos'}[page] || page
const image = (src, alt, cls='', eager=false) => `<img class="${cls}" src="${src}" alt="${esc(alt)}" loading="${eager?'eager':'lazy'}" decoding="async" ${eager?'fetchpriority="high"':''}>`
const btn = (text, href, secondary=false) => `<a class="button ${secondary?'button-outline':''}" href="${href}">${text}${icon('arrow')}</a>`
const textLink = (text, href) => `<a class="text-link" href="${href}">${text}${icon('arrow')}</a>`
const heading = (title, text='', tag='h2') => `<div class="heading"><${tag}>${title}</${tag}>${text?`<p>${text}</p>`:''}</div>`
const scene = (name, body, options={}) => `<section class="scene ${name}" data-network="${options.network||'edge'}" data-exit="${options.exit??''}" ${options.id?`id="${options.id}"`:''}>${body}</section>`
const photo = (src, caption, cls='') => `<figure class="field-photo ${cls}">${image(src,caption)}<figcaption>${esc(caption)}</figcaption></figure>`
const serviceImage = s => s.group==='automatizacion'?'/assets/experience/console-process.png':s.id==='vacuum'?art('vacuum'):s.photo
const serviceList = list => `<div class="service-list" data-pipe-port>${list.map(s=>`<a href="${link('servicio',s.id)}"><span>${esc(s.title)}</span>${icon('arrow')}</a>`).join('')}</div>`
const projectCard = p => `<a class="project-card" href="${link('proyecto',p.id)}" data-pipe-port>${image(p.photos[0],p.captions[0])}<div><span class="caption">${esc(p.location)}</span><h3>${esc(p.name)}</h3><p>${esc(p.title)}</p><span class="text-link">Ver proyecto ${icon('arrow')}</span></div></a>`
const articleCard = a => `<a class="article-card" href="${link('articulo',a.id)}" data-pipe-port>${image(a.image,a.illustration?'Ilustración conceptual: '+a.category:a.title)}<div><span class="caption">${a.category}${a.illustration?' · Ilustración conceptual':''}</span><h3>${a.title}</h3><p>${a.intro}</p><span class="text-link">Leer artículo ${icon('arrow')}</span></div></a>`
const crumb = (parent, name) => `<nav class="breadcrumb" aria-label="Ubicación"><a href="${link(parent)}">${nav.find(x=>x[0]===parent)[1]}</a><span>/</span><span>${esc(name)}</span></nav>`
const filters = options => `<div class="filters" role="group" aria-label="Filtrar contenido">${[['all','Todos'],...options].map(([v,n],i)=>`<button type="button" data-filter="${esc(v)}" aria-pressed="${i===0}">${esc(n)}</button>`).join('')}</div>`

function hero(title, text, src='/assets/experience/hero-faithful.png', actions='', cls='', breadcrumb='') {
  return scene(`hero ${src==='/assets/experience/hero-faithful.png'?'composed-hero':''} ${cls}`, `<div class="hero-media">${image(src,src.includes('/illustrations/')||src.includes('/experience/hero')?'Composición ilustrativa de equipos industriales SPS':'Equipo de campo del portafolio SPS','',true)}</div><div class="hero-copy">${breadcrumb}${heading(title,text,'h1')}<div class="actions">${actions}</div></div><a class="scroll-cue" href="#next-scene">Sigue el recorrido ${icon('arrow')}</a>`, {exit:.93})
}
function contactEnd(title='Conectemos tu<br><em>próxima operación.</em>', service='') {
  return scene('contact-ending', `<div class="ending-photo">${image(field('bajo-grande-patio-03.jpg'),'Patio y equipos SPS')}</div><div class="ending-copy">${heading(title,'Cuéntanos qué necesita tu operación y dónde se realizará el trabajo.')}<div class="actions">${btn('Hablemos de tu operación',link('contacto')+(service?'&servicio='+service:''))}${btn('0261 322 6494','tel:+582613226494',true)}</div></div><div class="contact-terminal" data-pipe-port>${icon('pin')}<span>San Francisco, Zulia<br><strong>Venezuela</strong></span></div>`, {exit:.9})
}
function history(full=false) {
  return scene(`history ${full?'history-hero':''}`, `<div class="history-top"><div>${heading(full?'Una historia<br><em>hecha en campo.</em>':'Quiénes somos.<br><em>Experiencia en campo.</em>',full?'Service Petroleum and Supply C.A.': '',full?'h1':'h2')}<p>Somos una empresa venezolana de servicios petroleros, con trayectoria desde 1990 y base en San Francisco, Zulia.</p>${textLink('Conoce nuestra historia',link('nosotros'))}</div><div class="year-block"><strong>1990</strong><p>Vapor, recuperación de crudo,<br>manejo de fluidos y automatización.</p></div></div><div class="history-landscape">${image('/assets/experience/history.png','Instalaciones y equipos en Bajo Grande')}</div>`, {exit:full?.93:.375,id:full?'':'next-scene'})
}
function categories() {
  return scene('categories', `<div class="category-landscape">${image('/assets/experience/services.png','Ilustración de servicios conectados')}</div>${heading('Servicios<br><em>que se conectan.</em>','Soluciones integrales para las necesidades de cada etapa de tu operación.')}<div class="category-grid pipe-collector">${groups.map((g,i)=>`<a class="category-card" href="${link('servicios')}#${g.id}" data-pipe-port="top"><div class="category-heading">${icon(['steam','drop','gear'][i])}<h3>${g.name}</h3></div><p>${g.intro}</p>${image(i===2?'/assets/experience/console-process.png':i===1?field('frac-tanks-modern-01.jpg'):g.image,i===2?'Ilustración de control industrial':g.caption)}<span class="text-link">Explorar servicios ${icon('arrow')}</span></a>`).join('')}</div>`,{network:'collector',exit:.65})
}
function equipment() {
  return scene('equipment', `${heading('Equipos<br><em>en acción.</em>','Capacidad para el manejo, almacenamiento y recuperación de fluidos.')}<div class="equipment-grid"><a href="${link('servicio','vacuum')}" class="vacuum-unit" data-pipe-port>${image(art('vacuum'),'Ilustración conceptual de una unidad vacuum')}<div class="equipment-label"><h3>Vacuum</h3><strong>160</strong><span>barriles</span></div><small>Vista ilustrativa</small></a><a href="${link('servicio','frac-tanks')}" class="tank-unit" data-pipe-port>${image(field('frac-tanks-modern-01.jpg'),'Frac tanks del patio SPS')}<div class="equipment-label"><h3>Frac tanks</h3><strong>500</strong><span>barriles</span></div></a></div>`,{exit:.60})
}
function control() {
  return scene('control', `<div class="control-copy">${heading('Del proceso<br><em>al dato.</em>','Instrumentación, control y telemetría para conocer lo que sucede en campo.')}<p>Integramos la medición con los sistemas de control y supervisión de pozos, estaciones y plantas industriales.</p>${textLink('Explorar automatización',link('servicios')+'#automatizacion')}</div><div class="control-system"><div class="transmitter" data-pipe-port="sensor">${image('/assets/experience/sensor-assembly.png','Ilustración de transmisor industrial')}<span class="station-label">Instrumentación</span></div><div class="console">${image('/assets/experience/console-process.png','Ilustración de gabinete PLC y monitor de supervisión')}<div class="console-labels"><span>PLC / RTU</span><span>SCADA</span></div></div></div><p class="illustration-caption">Representación conceptual de instrumentación, control y supervisión.</p>`,{network:'control',exit:.08})
}
function featured() { return scene('featured', `${heading('El trabajo se demuestra<br><em>en campo.</em>','Conoce las intervenciones y equipos que forman parte de nuestra experiencia.')}<div class="project-grid">${[projects[0],projects[2]].map(projectCard).join('')}</div>${textLink('Ver todos los proyectos',link('proyectos'))}`,{exit:.07}) }
function areas() { return scene('areas', `<div>${heading('Donde tu operación<br><em>nos necesita.</em>','Desde nuestra base en Zulia, atendemos necesidades de servicios petroleros e industriales.')}<div class="area-list">${['Pozos de producción','Estaciones','Patios de tanques','Fosas y recuperación','Plantas industriales'].map((n,i)=>`<a href="${link('servicios')}#${i===1||i===4?'automatizacion':'vapor'}">${n}${icon('arrow')}</a>`).join('')}</div></div>${photo(field('tia-juana-b5-01.jpg'),'Área de producción · Tía Juana','area-photo')}`,{exit:.92}) }
function home() { return hero('Experiencia<br>que mueve<br><em>tu operación.</em>','Vapor, recuperación de crudo y automatización para una operación más segura y eficiente.',undefined,btn('Explorar servicios',link('servicios'))+btn('Contactar',link('contacto'),true),'home-hero')+history()+categories()+equipment()+control()+featured()+areas()+contactEnd() }
function about() { return history(true)+scene('company split',`<div>${heading('Service Petroleum<br>and Supply C.A.','Una empresa venezolana enfocada en las necesidades del campo.')}<p>Trabajamos en recuperación de crudo, vapor, saneamiento, automatización y soporte industrial. Cada intervención requiere conocer la instalación, los equipos y las condiciones de la operación.</p><p>Nuestra base está en San Francisco, estado Zulia. Conectamos nuestra experiencia con las necesidades de pozos, estaciones, patios de tanques, fosas y plantas industriales.</p></div>${photo(field('frac-tanks-modern-01.jpg'),'Equipos del patio SPS')}`,{id:'next-scene',exit:.93})+categories()+scene('fleet',`${heading('Equipos y conocimiento<br><em>de la operación.</em>','La experiencia también se conoce a través de los equipos y los trabajos de campo.')}<div class="photo-pair">${photo(field('bajo-grande-caldera.jpg'),'Caldera portátil · Bajo Grande')}${photo(field('frac-tanks-modern-02.jpg'),'Frac tanks · Patio SPS')}</div>`,{exit:.08})+areas()+featured()+contactEnd() }
function catalogue() { return hero('Capacidad técnica.<br><em>Servicios conectados.</em>','Vapor, manejo de fluidos y control: explora cada área y conoce el alcance de sus servicios.',undefined,groups.map(g=>textLink(g.name,'#'+g.id)).join(''),'catalogue-hero')+categories()+groups.map((g,i)=>scene(`service-chapter chapter-${i}`,`<div class="chapter-intro">${heading(g.title,g.intro)}${photo(i===2?'/assets/experience/console-process.png':g.image,i===2?'Instrumentación y control · Vista ilustrativa':g.caption)}</div>${serviceList(services.filter(s=>s.group===g.id))}`,{id:g.id,exit:i%2?.93:.07})).join('')+contactEnd('¿Qué necesita<br><em>tu operación?</em>') }
function portfolio() { return hero('Proyectos.<br><em>Experiencia que se ve.</em>','Intervenciones, equipos y capacidades del portafolio de SPS.',field('bajo-grande-patio-03.jpg'),filters(groups.map(g=>[g.id,g.name])),'listing-hero')+`<div class="directory" id="next-scene">${projects.map((p,i)=>scene(`project-entry split ${i%2?'reverse':''}`,`<div class="project-copy"><span class="caption">${p.location}</span>${heading(p.name,p.title)}<p>${p.intro}</p>${btn('Ver el proyecto',link('proyecto',p.id))}</div>${photo(p.photos[0],p.captions[0])}`,{exit:i%2?.93:.07}).replace('<section ','<section data-filter-item data-category="'+p.group+'" ')).join('')}</div><p class="filter-empty" hidden>No hay proyectos en esta categoría.</p>`+contactEnd('Hablemos de tu<br><em>próximo trabajo.</em>') }
function editorial() { return hero('Conocimiento que<br><em>conecta con el campo.</em>','Artículos para entender los servicios, conocer los equipos y preparar una consulta técnica.',field('bajo-grande-patio-04.jpg'),filters([...new Set(articles.map(a=>a.category))].map(c=>[c,c])),'listing-hero')+`<div class="directory" id="next-scene">${articles.map((a,i)=>scene(`editorial-entry split ${i%2?'reverse':''}`,`<div><span class="caption">${a.category}</span>${heading(a.title,a.intro)}${btn('Leer artículo',link('articulo',a.id))}</div>${photo(a.image,a.illustration?'Vista ilustrativa':a.title)}`,{exit:i%2?.93:.07}).replace('<section ','<section data-filter-item data-category="'+a.category+'" ')).join('')}</div><p class="filter-empty" hidden>No hay artículos en esta categoría.</p>`+contactEnd() }
function serviceDetail(s) {
  const related=services.filter(x=>x.group===s.group&&x.id!==s.id).slice(0,3),p=projects.find(x=>x.id===s.project)
  return hero(esc(s.title),s.headline,serviceImage(s),btn('Consultar este servicio',link('contacto')+'&servicio='+s.id),'detail-hero',crumb('servicios',s.title))+
  scene('applications',`${heading(s.headline,s.description)}<div class="application-grid pipe-collector">${s.applications.map((a,i)=>`<div class="application" data-pipe-port="top">${icon(['pin','gear','drop'][i])}<h3>${a}</h3><p>${['El punto de partida es conocer la instalación y su necesidad.','La aplicación y las condiciones del área orientan el servicio.','La consulta permite definir los equipos y conexiones requeridos.'][i]}</p></div>`).join('')}</div>`,{id:'next-scene',network:'collector',exit:.07})+
  (s.group==='automatizacion'?control():scene('integration split',`<div>${heading('Del equipo<br><em>a la aplicación.</em>',s.description)}<div class="planning-list">${s.questions.map((x,i)=>`<div><span>${i+1}</span><h3>${x}</h3></div>`).join('')}</div></div>${photo(serviceImage(s),s.id==='vacuum'?'Vista ilustrativa':s.groupName)}`,{exit:.93}))+
  scene('evidence split reverse',`<div>${heading('Experiencia y equipos<br><em>en campo.</em>')}<h3>${p.name}</h3><p>${p.intro}</p>${textLink('Conocer el trabajo',link('proyecto',p.id))}</div>${photo(s.photo,'Registro del portafolio SPS')}`,{exit:.07})+
  scene('related',`${heading('Servicios<br><em>relacionados.</em>')}<div class="related-grid pipe-collector">${related.map(x=>`<a href="${link('servicio',x.id)}" data-pipe-port="top">${image(serviceImage(x),x.group==='automatizacion'?'Vista ilustrativa':x.title)}<h3>${x.title}</h3><span class="text-link">Ver servicio ${icon('arrow')}</span></a>`).join('')}</div>`,{network:'collector',exit:.93})+contactEnd('Hablemos de<br><em>este servicio.</em>',s.id)
}
function projectDetail(p) {
  return hero(esc(p.name),p.title,p.photos[0],btn('Consultar un trabajo similar',link('contacto')),'detail-hero',crumb('proyectos',p.name))+
  scene('project-story split',`<div>${heading('El trabajo<br><em>en campo.</em>',p.intro)}<p>${p.body}</p></div><div class="project-facts" data-pipe-port><h3>La operación, conectada.</h3><dl><dt>Ubicación</dt><dd>${p.location}</dd><dt>Área de servicio</dt><dd>${groups.find(g=>g.id===p.group).name}</dd><dt>Registro</dt><dd>Portafolio fotográfico SPS</dd></dl></div>`,{id:'next-scene',exit:.07})+
  scene('operation',`${heading('Una operación.<br><em>Varios puntos de conexión.</em>',p.body)}<div class="operation-photo">${image(p.photos.at(-1),p.captions.at(-1))}<div class="operation-tags">${p.services.slice(0,3).map(sid=>`<a data-pipe-port href="${link('servicio',sid)}">${services.find(s=>s.id===sid).title}${icon('arrow')}</a>`).join('')}</div></div>`,{exit:.93})+
  scene('project-gallery',`${heading('Registro<br><em>fotográfico.</em>','Amplía cada fotografía para conocer el equipo y el entorno de trabajo.')}<div class="gallery-grid">${p.photos.map((src,i)=>`<button class="gallery-open" data-full-image="${src}" data-caption="${esc(p.captions[i])}" aria-label="Ampliar ${esc(p.captions[i])}">${image(src,p.captions[i])}<span>${p.captions[i]}${icon('arrow')}</span></button>`).join('')}</div>`,{exit:.07})+
  scene('related split',`${heading('Equipos y servicios<br><em>relacionados.</em>')}${serviceList(p.services.map(sid=>services.find(s=>s.id===sid)))}`,{exit:.93})+
  scene('featured',`${heading('Más trabajos<br><em>en campo.</em>')}<div class="project-grid">${projects.filter(x=>x.id!==p.id).slice(0,2).map(projectCard).join('')}</div>`,{exit:.07})+contactEnd('¿Tu operación necesita<br><em>un servicio similar?</em>')
}
function articleDetail(a) {
  return hero(esc(a.title),a.intro,a.image,`<a class="text-link" href="#lectura-0">Comenzar lectura ${icon('arrow')}</a>`,'article-hero',crumb('articulos',a.category))+
  a.sections.map(([title,text],i)=>scene(`reading-scene ${i%2?'reading-reverse':''}`,`<div class="reading-index"><span>${String(i+1).padStart(2,'0')}</span><nav aria-label="Secciones del artículo">${a.sections.map(([t],n)=>`<a href="#lectura-${n}" ${i===n?'aria-current="location"':''}>${t}</a>`).join('')}</nav></div><article><h2>${title}</h2><p>${text}</p>${i===1?photo(a.image,a.illustration?'Esquema ilustrativo':a.title):`<div class="reading-links">${a.related.slice(i%2,i%2+2).map(sid=>textLink(services.find(s=>s.id===sid).title,link('servicio',sid))).join('')}</div>`}</article>`,{id:'lectura-'+i,exit:i%2?.93:.07})).join('')+
  scene('article-close',`${heading('Sigue conectando<br><em>con el campo.</em>')}${a.source?`<p class="source">Para ampliar: <a href="${esc(a.source[1])}" target="_blank" rel="noopener noreferrer">${esc(a.source[0])}</a></p>`:''}<div class="article-grid">${articles.filter(x=>x.id!==a.id).slice(0,2).map(articleCard).join('')}</div>${btn('Consultar con SPS',link('contacto'))}`,{exit:.93})
}
function contact() {
  return hero('Conectemos<br><em>tu operación.</em>','Vapor, recuperación de crudo, manejo de fluidos y automatización. Cuéntanos qué necesitas.',undefined,btn('Preparar consulta','#solicitud')+btn('Llamar','tel:+582613226494',true),'contact-hero')+
  scene('contact-methods',`${heading('Hablemos<br><em>directamente.</em>')}<div class="method-grid pipe-collector"><a href="tel:+582613226494" data-pipe-port="top">${icon('phone')}<h3>Llámanos</h3><strong>0261 322 6494</strong><p>Atención desde nuestra base en Zulia.</p></a><a href="https://wa.me/584146361373" target="_blank" rel="noopener noreferrer" data-pipe-port="top">${icon('whatsapp')}<h3>WhatsApp</h3><strong>+58 414 636 1373</strong><p>Comparte la necesidad de tu operación.</p></a><a href="#ubicacion" data-pipe-port="top">${icon('pin')}<h3>Visítanos</h3><strong>San Francisco, Zulia</strong><p>Av. 5, Calle 13, N.º 26A-162</p></a></div>`,{id:'next-scene',network:'collector',exit:.07})+
  scene('contact-form split',`<div>${heading('Cuéntanos qué<br><em>necesita tu operación.</em>','Prepara un resumen para compartirlo con SPS. También puedes llamarnos directamente.')}${photo(field('frac-tanks-modern-01.jpg'),'Frac tanks · Patio SPS')}</div><form id="request-form" data-pipe-port><div class="form-fields"><label>Nombre<input name="Nombre" autocomplete="name" required maxlength="120"></label><label>Empresa (opcional)<input name="Empresa" autocomplete="organization" maxlength="160"></label><label>Teléfono<input name="Teléfono" type="tel" autocomplete="tel" required maxlength="50"></label><label>Servicio de interés<select name="Servicio" required><option value="">Selecciona un servicio</option>${groups.map(g=>`<optgroup label="${g.name}">${services.filter(s=>s.group===g.id).map(s=>`<option ${q.get('servicio')===s.id?'selected':''}>${s.title}</option>`).join('')}</optgroup>`).join('')}<option>Necesito orientación</option></select></label><label class="full">Ubicación del trabajo<input name="Ubicación" required maxlength="200"></label><label class="full">Describe tu necesidad<textarea name="Necesidad" rows="4" required maxlength="4000"></textarea></label></div><button class="button" type="submit">Preparar solicitud ${icon('arrow')}</button><p class="form-note">Descarga un resumen; no envía la solicitud.</p><p id="form-status" role="status"></p></form>`,{id:'solicitud',exit:.93})+
  scene('planning',`${heading('Una consulta clara<br><em>empieza en campo.</em>')}<div class="planning-grid pipe-collector">${[['Describe tu necesidad','Indica el trabajo, el equipo o la situación que necesitas atender.'],['Comparte la ubicación','Estado, municipio y referencia del área de trabajo.'],['Añade información técnica','Modelos, capacidades conocidas, fotografías o planos disponibles.']].map(([t,d],i)=>`<div data-pipe-port="top"><span class="step">${i+1}</span><h3>${t}</h3><p>${d}</p></div>`).join('')}</div>`,{network:'collector',exit:.07})+
  scene('location split',`<div>${heading('Nuestra base<br><em>está en Zulia.</em>')}<address>Av. 5, Calle 13, N.º 26A-162<br>San Francisco, Maracaibo<br>Zulia, Venezuela.</address>${btn('Llamar para coordinar','tel:+582613226494')}</div>${photo(field('patio-vapor-01.jpg'),'Equipos del portafolio SPS')}`,{id:'ubicacion',exit:.93})+contactEnd('Seguimos impulsando<br><em>tu operación.</em>')
}

document.body.dataset.page=page
document.getElementById('site-header').innerHTML=`<div class="header-inner"><a class="brand" href="${link('inicio')}" aria-label="SPS, inicio">${image('/assets/experience/logo.png','Service Petroleum and Supply C.A.','',true)}</a><nav id="main-nav" aria-label="Principal">${nav.map(([p,n])=>`<a href="${link(p)}" ${active===p?'aria-current="page"':''}>${n}</a>`).join('')}</nav><a class="header-contact" href="${link('contacto')}">${icon('mail')}Contáctanos${icon('arrow')}</a><button class="menu-toggle" aria-controls="main-nav" aria-expanded="false" aria-label="Abrir menú"><span></span><span></span></button></div>`
const record=page==='servicio'?services.find(s=>s.id===id):page==='proyecto'?projects.find(p=>p.id===id):page==='articulo'?articles.find(a=>a.id===id):null
const gallery=galleryPages({image,btn,textLink,heading,scene,photo,hero,control,serviceList,filters,crumb,esc,link})
const routes={inicio:gallery.home,nosotros:gallery.about,servicios:gallery.catalogue,proyectos:gallery.portfolio,articulos:gallery.editorial,contacto:contact}
main.innerHTML=routes[page]?routes[page]():record?(page==='servicio'?gallery.serviceDetail(record):page==='proyecto'?gallery.projectDetail(record):gallery.articleDetail(record)):scene('not-found',`${heading('Esta página no está disponible.','Explora los servicios o vuelve al inicio.','h1')}${btn('Volver al inicio',link('inicio'))}`)
document.title=`${record?.title||nav.find(n=>n[0]===page)?.[1]||'Página no disponible'} · SPS`
document.getElementById('site-footer').innerHTML=`<div class="footer-inner"><a class="brand" href="${link('inicio')}" aria-label="SPS, inicio">${image('/assets/experience/logo.png','SPS')}</a><nav aria-label="Navegación al pie">${nav.map(([p,n])=>`<a href="${link(p)}">${n}</a>`).join('')}</nav><p>San Francisco, Zulia<br>Venezuela</p><a href="#content" class="back-top" aria-label="Volver arriba">${icon('up')}</a></div><div class="footer-bottom"><span>Service Petroleum and Supply C.A.</span><a href="tel:+582613226494">0261 322 6494</a></div>`
const menu=document.querySelector('.menu-toggle'),navigation=document.querySelector('#main-nav')
function closeMenu(){menu.setAttribute('aria-expanded','false');navigation.classList.remove('open');menu.setAttribute('aria-label','Abrir menú')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');navigation.classList.toggle('open',open)})
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()})
navigation.addEventListener('click',closeMenu)
const network=mountNetwork(main,page)
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const items=[...document.querySelectorAll('[data-filter-item]')];items.forEach(item=>item.hidden=button.dataset.filter!=='all'&&item.dataset.category!==button.dataset.filter);document.querySelector('.filter-empty').hidden=items.some(item=>!item.hidden);network.rebuild()}))
document.querySelector('#request-form')?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),blob=new Blob(['Solicitud de servicio · SPS\n\n'+[...data].map(([k,v])=>`${k}: ${v}`).join('\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='solicitud-sps.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#form-status').textContent='Resumen descargado. Aún no se ha enviado a SPS. Compártelo al contactar.'})
if(document.querySelector('.gallery-open')){const dialog=document.createElement('dialog');dialog.className='photo-dialog';dialog.innerHTML='<button class="dialog-close" aria-label="Cerrar fotografía">Cerrar ×</button><figure><figcaption></figcaption></figure>';document.body.append(dialog);document.querySelectorAll('.gallery-open').forEach(b=>b.addEventListener('click',()=>{let expanded=dialog.querySelector('img');if(!expanded){expanded=document.createElement('img');dialog.querySelector('figure').prepend(expanded)}expanded.src=b.dataset.fullImage;expanded.alt=b.dataset.caption;dialog.querySelector('figcaption').textContent=b.dataset.caption;dialog.showModal()}));dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()})}
if(location.hash)requestAnimationFrame(()=>document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView())
