import {groups as originalGroups} from './catalogue.js'
export const field = name => '/assets/experience/field/'+name
export const art = name => '/assets/experience/illustrations/'+name+'.png'
export const slug = text => text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
export const groups = originalGroups.map(g=>({...g, image:field(g.image)}))
const details = [
 ['calderas-portatiles','Calderas portátiles para llevar el vapor al trabajo en campo.','El alquiler de calderas portátiles forma parte de la capacidad de SPS para atender necesidades de vapor en instalaciones petroleras. La ubicación, la aplicación y las condiciones del área permiten definir el alcance de cada consulta.',['Pozos de producción','Patios de tanques','Fosas y áreas de recuperación'],'bajo-grande-caldera.jpg',['Ubicación del equipo','Aplicación del vapor','Tiempo previsto de trabajo'],'bajo-grande'],
 ['vapor-a-pozos','Vapor para las necesidades del pozo.','SPS ofrece inyección de vapor a pozos. El servicio se consulta a partir de las características de la instalación y del trabajo requerido, considerando el equipo disponible en sitio y la conexión con la operación.',['Pozos de producción','Áreas de operación','Estaciones de campo'],'tia-juana-b5-01.jpg',['Identificación del pozo','Condiciones del área','Necesidad de vapor'],'tia-juana'],
 ['vapor-patios-tanques','El vapor acompaña el manejo del crudo.','La inyección de vapor para patios de tanques atiende necesidades de calentamiento dentro de las operaciones de almacenamiento. La disposición de los tanques y líneas es parte de la información necesaria para orientar el servicio.',['Patios de tanques','Áreas de almacenamiento','Manejo de crudo'],'patio-vapor-01.jpg',['Tanques involucrados','Conexiones existentes','Condición del producto'],'bajo-grande'],
 ['calentamiento-crudo-pit','Calentamiento aplicado a la recuperación de crudo.','El calentamiento de crudo en Pit es uno de los trabajos del portafolio de SPS. La intervención conecta calderas, líneas y sistemas auxiliares con las necesidades del área donde se encuentra el crudo.',['Pit','Fosas','Áreas de recuperación'],'bajo-grande-caldera.jpg',['Ubicación del Pit','Características del crudo','Acceso al área'],'bajo-grande'],
 ['recuperacion-fosas','Recuperación de hidrocarburos en áreas de campo.','SPS contempla la recuperación de crudo en fosas de pasivos ambientales dentro de sus servicios con vapor. La evaluación del área, del material y de los medios de manejo permite conversar sobre el alcance del trabajo.',['Fosas con hidrocarburos','Pasivos ambientales','Recuperación de crudo Slop'],'boscan-slop-antes.jpg',['Descripción de la fosa','Material presente','Condiciones de acceso'],'campo-boscan'],
 ['sellos-bomba','Calentamiento para sellos de bomba en carga de buques.','Este servicio se orienta al calentamiento de sellos de bomba vinculados con operaciones de carga de buques. Para definir una consulta son relevantes los datos de la bomba, la aplicación y la instalación donde se requiere atención.',['Sistemas de bombeo','Carga de buques','Manejo de hidrocarburos'],'bajo-grande-patio-04.jpg',['Datos de la bomba','Ubicación del sello','Condiciones del trabajo'],'bajo-grande'],
 ['mantenimiento-calentadores','Atención técnica para calentadores.','SPS incluye reparación y mantenimiento de calentadores en su oferta industrial. La consulta debe describir el equipo, su condición actual y la necesidad de intervención, para establecer un alcance acorde con el caso.',['Calentadores','Sistemas térmicos','Instalaciones industriales'],'patio-vapor-02.jpg',['Identificación del calentador','Falla o necesidad observada','Disponibilidad para intervención'],'bajo-grande'],
 ['mantenimiento-calderas','Mantenimiento de los equipos que generan vapor.','La reparación y el mantenimiento de calderas complementan los servicios de vapor de SPS. Los antecedentes del equipo y la condición reportada orientan la conversación técnica antes de definir los trabajos.',['Calderas','Equipos portátiles','Sistemas de vapor'],'bajo-grande-caldera.jpg',['Datos de la caldera','Historial disponible','Necesidad de mantenimiento'],'bajo-grande'],
 ['saneamiento-hidrojet','Limpieza de áreas contaminadas con petróleo.','El saneamiento mediante hidrojet forma parte de la atención de áreas contaminadas con petróleo. La descripción de las superficies y del área afectada permite plantear el trabajo junto con las necesidades de manejo de los materiales recuperados.',['Superficies contaminadas','Áreas petroleras','Instalaciones de campo'],'boscan-fosa-03.jpg',['Área afectada','Superficies a atender','Material presente'],'san-francisco'],
 ['bombeo-crudo','Movimiento de crudo entre puntos de operación.','El bombeo de crudo atiende necesidades de transferencia dentro de las instalaciones. Los puntos de origen y destino, las características del producto y las conexiones disponibles son información clave para consultar este servicio.',['Transferencia de crudo','Patios de tanques','Áreas de recuperación'],'bajo-grande-patio-02.jpg',['Origen y destino','Características del fluido','Conexiones y recorrido'],'bajo-grande'],
 ['vacuum','Trasegado con unidades vacuum de 160 barriles.','El servicio de trasegado con vacuum permite atender necesidades de manejo de fluidos. La capacidad publicada para este equipo es de 160 barriles; la aplicación y las condiciones del trabajo se revisan para cada solicitud.',['Manejo de fluidos','Trasegado','Áreas de saneamiento'],'boscan-fosa-04.jpg',['Fluido a manejar','Volumen estimado','Acceso y destino'],'san-francisco'],
 ['frac-tanks','Almacenamiento temporal con Frac Tanks de 500 barriles.','SPS ofrece alquiler de Frac Tank con capacidad de 500 barriles. El portafolio muestra equipos con estructuras, escaleras y conexiones para almacenamiento temporal en operaciones petroleras.',['Almacenamiento temporal','Patios de operación','Manejo de fluidos'],'frac-tanks-modern-01.jpg',['Producto a almacenar','Tiempo requerido','Espacio y conexiones'],'patio-sps'],
 ['soldadura','Equipos de soldadura movilizados al trabajo.','Los camiones con equipos de soldadura forman parte del soporte industrial de SPS. Para orientar la consulta se requiere identificar el elemento a intervenir, su ubicación y las condiciones del área.',['Soporte de campo','Elementos industriales','Trabajos de soldadura'],'bajo-grande-patio-04.jpg',['Elemento a intervenir','Material y dimensiones','Ubicación del trabajo'],'bajo-grande'],
 ['desechos-derrames','Manejo temporal de materiales provenientes de derrames.','La disposición temporal de desechos provenientes de derrames complementa las labores de saneamiento. El tipo de material, su cantidad estimada y la ubicación son datos necesarios para revisar el alcance específico.',['Desechos petrolizados','Áreas afectadas por derrames','Saneamiento'],'boscan-fosa-03.jpg',['Tipo de material','Cantidad estimada','Ubicación y manejo previsto'],'san-francisco'],
 ['telemetria','Recuperar la comunicación entre el campo y la supervisión.','La rehabilitación de telemetría de pozos y estaciones se centra en las necesidades de comunicación y seguimiento de la instalación. El inventario de equipos y la condición del sistema existente permiten orientar la consulta.',['Pozos','Estaciones','Comunicaciones de campo'],'bajo-grande-patio-04.jpg',['Equipos instalados','Medios de comunicación','Condición del sistema'],'automatizacion'],
 ['plc','Programación de PLC para estaciones.','SPS incluye programación de PLC en estaciones dentro de sus servicios de automatización. La identificación del controlador y de las funciones requeridas ayuda a definir el trabajo y su relación con los equipos de campo.',['Estaciones','Control de procesos','Integración de equipos'],'bajo-grande-patio-04.jpg',['Modelo del PLC','Funciones requeridas','Documentación disponible'],'automatizacion'],
 ['rtu','Control y comunicación para pozos de producción e inyección.','La programación de RTU se orienta a pozos de producción e inyección de agua. La información sobre señales, comunicaciones y operación permite plantear la integración de la unidad con el sistema existente.',['Pozos de producción','Inyección de agua','Telemetría'],'tia-juana-b5-02.jpg',['Modelo de RTU','Señales de campo','Comunicación existente'],'automatizacion'],
 ['scada','Supervisión conectada con los procesos de campo.','El servicio SCADA Wonderware CIBO forma parte de la oferta de SPS. Para consultar un trabajo es útil describir la plataforma instalada, las variables que se necesitan visualizar y los equipos con los que se debe comunicar.',['Supervisión','Estaciones','Visualización de procesos'],'bajo-grande-patio-04.jpg',['Plataforma y versión','Variables requeridas','Controladores conectados'],'automatizacion'],
 ['variadores-bcp','Variadores y RTU en pozos con bombas BCP.','SPS contempla variadores de pozos con bombas BCP y sus RTU dentro de la automatización de campo. El servicio se consulta a partir de los datos del accionamiento, la bomba y la integración de control existente.',['Pozos con bombas BCP','Accionamientos','Integración con RTU'],'tia-juana-b5-01.jpg',['Datos del variador','Datos de la bomba','Control y comunicación'],'automatizacion'],
 ['instrumentacion','La información de la operación empieza en el instrumento.','La instrumentación de pozos y estaciones conecta las variables de campo con las necesidades de control y supervisión. La consulta debe identificar qué se requiere medir y cómo se integrará la señal al sistema.',['Pozos','Estaciones','Variables de proceso'],'bajo-grande-patio-04.jpg',['Variable a medir','Instrumentos instalados','Sistema de destino'],'automatizacion'],
 ['puesta-tierra','Puesta a tierra y protección de pararrayos.','Estos sistemas forman parte del soporte eléctrico de SPS para instalaciones de campo. Los datos de la instalación y la documentación existente son el punto de partida para consultar el alcance de una intervención.',['Instalaciones de campo','Sistemas eléctricos','Protección de instalaciones'],'bajo-grande-patio-04.jpg',['Ubicación y planos','Instalación existente','Necesidad de intervención'],'automatizacion'],
 ['solar-telemetria','Energía para telemetría en pozos sin electricidad.','SPS ofrece paneles solares para telemetría en pozos sin electricidad. La consulta debe describir los equipos que se necesitan alimentar, la ubicación y las condiciones del sistema de comunicación.',['Pozos sin electricidad','Telemetría','Sistemas remotos'],'tia-juana-b5-01.jpg',['Equipos a alimentar','Ubicación del pozo','Sistema de telemetría'],'automatizacion'],
]
let index=0
export const services=groups.flatMap(g=>g.items.map(title=>{const [id,headline,description,applications,photo,questions,project]=details[index++];return {id,title,headline,description,applications,photo:field(photo),questions,project,group:g.id,groupName:g.name}}))
export const projects=[
 {id:'campo-boscan',name:'Campo Boscán',title:'Calentamiento y recuperación de crudo Slop',location:'Campo Boscán · Estación 1',group:'vapor',intro:'Recuperación de crudo con vapor en fosas, con registro fotográfico de la intervención.',body:'El portafolio de SPS documenta labores de calentamiento y recuperación de crudo Slop en la Estación 1 de Campo Boscán. Las fotografías muestran el área de trabajo y los elementos utilizados durante la intervención.',photos:['boscan-slop-antes.jpg','boscan-slop-despues.jpg','boscan-fosa-01.jpg'],captions:['Registro inicial de la fosa','Registro posterior de la intervención','Área de recuperación'],services:['recuperacion-fosas','calderas-portatiles','bombeo-crudo']},
 {id:'tia-juana',name:'Tía Juana',title:'Inyección de vapor a pozos',location:'PDVSA Tía Juana · Estación B5',group:'vapor',intro:'Operación con equipos movilizados en estación y áreas de producción.',body:'La experiencia publicada incluye inyección de vapor a pozos en la Estación B5 de Tía Juana. El registro permite conocer el entorno de producción donde se desarrolló el trabajo y su relación con las instalaciones de campo.',photos:['tia-juana-b5-01.jpg','tia-juana-b5-02.jpg'],captions:['Área de producción · Estación B5','Registro de campo · Tía Juana'],services:['vapor-a-pozos','calderas-portatiles']},
 {id:'bajo-grande',name:'Bajo Grande',title:'Calentamiento de crudo en Pit',location:'PDVSA Bajo Grande',group:'vapor',intro:'Instalación de caldera, tanques, líneas y sistemas auxiliares para el manejo de crudo.',body:'El trabajo en Bajo Grande reúne caldera, tanques, líneas y sistemas auxiliares para el calentamiento y manejo de crudo. Las imágenes del portafolio muestran el equipo portátil y la disposición de los elementos en el patio.',photos:['bajo-grande-caldera.jpg','bajo-grande-patio-02.jpg','bajo-grande-patio-04.jpg'],captions:['Caldera portátil en Bajo Grande','Vista del patio y las conexiones','Equipos de campo'],services:['calentamiento-crudo-pit','calderas-portatiles','vapor-patios-tanques']},
 {id:'san-francisco',name:'San Francisco–La Cañada',title:'Saneamiento por derrames de hidrocarburos',location:'Costas de San Francisco–La Cañada',group:'manejo',intro:'Saneamiento y disposición temporal de desechos en áreas afectadas por hidrocarburos.',body:'El portafolio recoge trabajos de saneamiento y disposición temporal de desechos provenientes de áreas afectadas por derrames. La atención de estos espacios forma parte de los servicios de manejo y saneamiento de SPS.',photos:['boscan-fosa-03.jpg','boscan-fosa-04.jpg'],captions:['Registro de saneamiento del portafolio','Área de intervención'],services:['saneamiento-hidrojet','desechos-derrames','vacuum']},
 {id:'patio-sps',name:'Patio SPS',title:'Frac tanks para almacenamiento temporal',location:'Patio SPS · Zulia',group:'manejo',intro:'Tanques con estructuras, escaleras y conexiones para operaciones petroleras.',body:'La capacidad de almacenamiento temporal se muestra en los Frac Tanks del patio SPS. Los equipos publicados incluyen estructuras, escaleras y conexiones; el servicio de alquiler contempla tanques de 500 barriles.',photos:['frac-tanks-modern-01.jpg','frac-tanks-modern-02.jpg','frac-tank-line-01.jpg'],captions:['Frac Tanks · Vista frontal','Estructuras y accesos','Línea de equipos del patio'],services:['frac-tanks','bombeo-crudo']},
 {id:'automatizacion',name:'Automatización e instrumentación',title:'Control y comunicación de campo',location:'Estaciones y plantas industriales',group:'automatizacion',intro:'Soporte en telemetría, RTU, PLC, instrumentación, puesta a tierra y comunicación.',body:'La capacidad de automatización de SPS abarca instrumentación, control y comunicaciones para pozos, estaciones y plantas. Este registro del portafolio presenta esa área de servicio junto con fotografías del entorno de campo; los esquemas de control son ilustrativos.',photos:['bajo-grande-patio-04.jpg','bajo-grande-patio-01.jpg'],captions:['Entorno de campo del portafolio SPS','Instalaciones y equipos de campo'],services:['instrumentacion','plc','rtu','scada']},
].map(p=>({...p,photos:p.photos.map(field)}))
export const articles=[
 {id:'vapor-recuperacion',title:'Cómo interviene el vapor en la recuperación de crudo',category:'Vapor',image:field('bajo-grande-caldera.jpg'),intro:'Una introducción al papel del calentamiento y a los servicios de vapor del portafolio SPS.',sections:[['El vapor como medio de calentamiento','Una caldera transfiere calor al agua para generar vapor. Este puede transportar energía térmica hasta una aplicación de proceso. El circuito de generación de vapor y el producto que recibe calor cumplen funciones distintas.'],['Del equipo a la aplicación','En el portafolio de SPS aparecen inyección de vapor a pozos, patios de tanques, calentamiento de crudo en Pit y recuperación en fosas. Cada trabajo tiene condiciones propias: no basta con elegir un equipo sin conocer dónde se utilizará.'],['La información del trabajo','Para conversar sobre una necesidad de vapor conviene reunir la ubicación, el propósito del calentamiento y los datos disponibles de la instalación. Esa información permite orientar la consulta y definir qué aspectos deben revisarse en campo.'],['Experiencia que se puede consultar','Bajo Grande y Campo Boscán son dos referencias del portafolio vinculadas al calentamiento y recuperación de crudo. Sus páginas reúnen descripciones y fotografías del trabajo publicado por SPS.']],related:['calderas-portatiles','calentamiento-crudo-pit'],source:['Fundamentos del vapor · Spirax Sarco','https://content.spiraxsarco.com/-/media/spiraxsarco/opco/gb/promo/campaign-documents/fundamentals_of_steam_quick_start_guide.ashx?rev=8302c8c509c44636bb3062cc292e922e']},
 {id:'elegir-frac-tank',title:'Qué considerar al consultar un Frac Tank',category:'Equipos',image:field('frac-tanks-modern-01.jpg'),intro:'Los datos de tu operación ayudan a orientar una solicitud de almacenamiento temporal.',sections:[['Definir la necesidad','El punto de partida es describir qué se necesita almacenar, en qué ubicación y durante cuánto tiempo. El alquiler de un tanque se relaciona con una operación concreta y con su forma de recibir y transferir el producto.'],['Capacidad publicada','SPS incluye Frac Tanks de 500 barriles en su catálogo. Esta capacidad es un dato del equipo; para consultar el servicio también es necesario explicar el volumen previsto y las condiciones del trabajo.'],['Espacio y conexiones','Compartir información del acceso, del espacio disponible y de las conexiones existentes facilita la conversación. Fotografías del área y datos de los equipos relacionados pueden acompañar la solicitud.'],['Conocer el equipo','Las fotografías del Patio SPS permiten observar estructuras, escaleras y conexiones de los tanques del portafolio. Desde ese proyecto se puede abrir la ficha del servicio y preparar una consulta específica.']],related:['frac-tanks','bombeo-crudo']},
 {id:'instrumento-scada',title:'Del instrumento al SCADA: el recorrido de un dato',category:'Automatización',image:art('control'),illustration:true,intro:'Medición, control y supervisión: tres funciones que se conectan en una instalación.',sections:[['Medir en campo','Un instrumento permite obtener información de una variable del proceso. Presión, temperatura o nivel son ejemplos habituales. La selección del instrumento depende de la necesidad de medición y de las condiciones de la aplicación.'],['Llevar la información al sistema','Controladores como PLC y RTU pueden recibir señales de campo y comunicarlas al sistema de supervisión. La arquitectura y los protocolos dependen de los equipos instalados.'],['Visualizar en el SCADA','Un sistema SCADA reúne información del proceso y la presenta al operador. Puede incluir pantallas, tendencias y alarmas según la configuración del proyecto. La ilustración de esta página representa ese recorrido; no muestra una operación en vivo.'],['Consultar una integración','Para SPS, una consulta puede comenzar con la lista de instrumentos, el controlador disponible y la plataforma de supervisión. Identificar lo que ya existe y lo que se necesita incorporar ayuda a delimitar el servicio.']],related:['instrumentacion','plc','rtu','scada'],source:['Qué es SCADA · Inductive Automation','https://inductiveautomation.com/resources/article/what-is-scada']},
 {id:'vacuum-bombeo',title:'Vacuum y bombeo en el manejo de fluidos',category:'Manejo de fluidos',image:art('vacuum'),illustration:true,intro:'Dos servicios del catálogo de SPS que conviene consultar a partir del trabajo requerido.',sections:[['Empezar por el trabajo','Una solicitud de manejo de fluidos necesita describir el producto, su ubicación y el destino previsto. Hablar primero de la necesidad permite orientar la consulta sin asumir que todos los trabajos requieren el mismo equipo.'],['El servicio de vacuum','El catálogo de SPS contempla trasegado con vacuum de 160 barriles. Al solicitarlo, conviene indicar el volumen estimado, los accesos al área y la información disponible sobre el fluido.'],['El servicio de bombeo','El bombeo de crudo es otra de las capacidades publicadas. Para conversar sobre él son importantes los puntos de origen y destino, el recorrido y las conexiones disponibles.'],['Un recorrido relacionado','El saneamiento, el almacenamiento temporal y la disposición temporal de desechos son servicios que pueden motivar consultas relacionadas. Su alcance debe definirse para cada operación; la ilustración muestra el concepto de manejo de fluidos.']],related:['vacuum','bombeo-crudo','frac-tanks']},
 {id:'telemetria-campo',title:'Telemetría en pozos y estaciones: qué informar al consultar',category:'Automatización',image:field('tia-juana-b5-01.jpg'),intro:'Una consulta técnica empieza por conocer los equipos y las comunicaciones existentes.',sections:[['Identificar la instalación','Indica si la consulta corresponde a un pozo de producción, una estación o un pozo de inyección de agua. El catálogo de SPS contempla rehabilitación de telemetría y programación de RTU en estos entornos.'],['Describir la condición actual','Explica qué equipos están instalados y cuál es la necesidad observada. Una lista de modelos, fotografías y documentación disponible ayuda a presentar el caso con claridad.'],['Reunir los datos de comunicación','Cuando existan, incluye los datos del medio de comunicación y del sistema al que debe llegar la información. La consulta puede involucrar instrumentos, RTU, controladores y supervisión.'],['Considerar la alimentación','Para pozos sin electricidad, SPS incluye paneles solares para telemetría en su oferta. Describe los equipos a alimentar y la ubicación para orientar una consulta sobre esa necesidad específica.']],related:['telemetria','rtu','solar-telemetria']},
 {id:'preparar-consulta',title:'Preparar una consulta técnica sobre tu operación',category:'Equipos',image:field('bajo-grande-patio-02.jpg'),intro:'Información concreta para comenzar una conversación sobre servicios de campo.',sections:[['Explica la necesidad','Describe con tus propias palabras qué trabajo necesitas: vapor, recuperación, bombeo, almacenamiento, saneamiento o automatización. Si no conoces el nombre del servicio, explica la situación que quieres atender.'],['Comparte la ubicación','Indica el área de trabajo y los datos de acceso disponibles. Para equipos móviles, las características del lugar forman parte de la conversación sobre la operación.'],['Añade información del equipo','Los modelos, las capacidades conocidas, las fotografías y los planos disponibles pueden facilitar la consulta. No es necesario inventar un dato que no tienes; basta con indicar que debe revisarse.'],['Contacta con SPS','La página de contacto permite preparar un resumen para descargar y compartir. También muestra los números de contacto directo. La descarga por sí sola no envía la solicitud a SPS.']],related:['calderas-portatiles','frac-tanks','instrumentacion']},
]
