import {groups,services,projects,articles,field} from './content.js'
import {icon} from './icons.js'

// Layouts follow the user's nine full-page compositions. Each page owns its
// editorial arrangement; the shared network only supplies connected fittings.
export function galleryPages(ui){
 const {image,btn,textLink,heading,scene,photo,hero,control,serviceList,filters,crumb,esc,link}=ui
 const asset=n=>'/assets/experience/'+n+'.png'
 const phoneCard=()=>`<aside class="phone-card" data-pipe-port><a href="tel:+582613226494">${icon('phone')}<strong>0261 322 6494</strong></a><a href="https://wa.me/584146361373" target="_blank" rel="noopener noreferrer">${icon('whatsapp')}<strong>+58 414 636 1373</strong></a>${btn('Contáctanos ahora',link('contacto'))}</aside>`
 const close=(title='Conectemos<br><em>tu próxima operación.</em>')=>scene('gallery-close',`<div>${heading(title,'Hablemos de tu proyecto y de las necesidades de tu operación.')}</div>${phoneCard()}`,{network:'terminal',exit:.93})
 const workCard=p=>`<a class="work-picture" href="${link('proyecto',p.id)}" data-pipe-port>${image(p.photos[0],p.captions[0])}<div><h3>${p.name}</h3><p>${p.title}</p><span aria-hidden="true">${icon('arrow')}</span></div></a>`
 const work=(title='Trabajos<br><em>en campo.</em>')=>scene('gallery-work',`<div>${heading(title,'Soluciones y equipos en las condiciones reales del trabajo en campo.')}${btn('Ver proyectos',link('proyectos'),true)}</div><div class="work-pictures">${[projects[0],projects[2]].map(workCard).join('')}</div>`,{exit:.93})
 const areaRecords=[['Pozos','Pozos productores e inyectores.','tia-juana-b5-01.jpg','pin'],['Estaciones','Servicios para instalaciones de superficie.','bajo-grande-patio-04.jpg','gear'],['Patios','Manejo y almacenamiento de equipos y fluidos.','frac-tanks-modern-01.jpg','drop'],['Fosas','Saneamiento y recuperación de hidrocarburos.','boscan-fosa-03.jpg','steam'],['Plantas','Soporte industrial y servicios complementarios.','patio-vapor-01.jpg','gear']]
 const areas=()=>scene('gallery-areas',`<div>${heading('Áreas<br><em>de trabajo.</em>','Servicios para distintas instalaciones de la operación.')}</div><div class="area-columns">${areaRecords.map(([title,text,src,i])=>`<a href="${link('servicios')}">${image(field(src),title+' · Portafolio SPS')}${icon(i)}<h3>${title}</h3><p>${text}</p></a>`).join('')}</div>`,{exit:.07})
 const categories=(mode='home')=>scene('gallery-categories category-'+mode,`${mode!=='strip'?heading(mode==='photo'?'Nuestra experiencia<br><em>se conecta.</em>':'Servicios<br><em>que se conectan.</em>',mode==='photo'?'Integramos capacidades para las necesidades de la operación.':'Soluciones integrales para cada etapa de tu operación.'):''}<div class="gallery-cards pipe-collector">${groups.map((g,i)=>`<a class="gallery-service-card" href="${link('servicios')}#${g.id}" data-pipe-port="top">${mode==='photo'?image(i===2?asset('console-process'):g.image,i===2?'Ilustración de control industrial':g.caption):''}<div class="card-body"><div class="card-heading">${icon(['steam','drop','gear'][i])}<h3>${g.name}</h3></div><p>${g.intro}</p><span class="text-link">Conocer más <span class="round-arrow">${icon('arrow')}</span></span></div></a>`).join('')}</div>`,{network:'collector',exit:.93})
 const history=()=>scene('gallery-history',`<div class="history-copy">${heading('Quiénes somos')}<p><strong>Service Petroleum and Supply C.A.</strong> es una empresa venezolana de servicios petroleros, fundada en 1990 y con base en San Francisco, Zulia.</p><p>Contamos con experiencia en recuperación de crudo, generación de vapor, manejo y saneamiento de fluidos, automatización y soporte industrial para la industria petrolera y energética.</p>${btn('Conoce nuestra historia',link('nosotros'))}</div><div class="history-date"><strong>1990</strong><p>Al servicio de la industria petrolera venezolana.</p></div><div class="gallery-history-photo">${image(asset('history-faithful'),'Composición ilustrativa de instalaciones y equipos SPS')}</div>`,{exit:.375,id:'next-scene'})
 const equipment=()=>scene('gallery-equipment',`<div class="equipment-intro">${heading('Equipos<br><em>en acción.</em>','Tecnología y equipos para las necesidades de tu operación.')}</div><div class="equipment-world">${image(asset('equipment-world'),'Ilustración conceptual de vacuum, frac tanks y circuito de vapor')}</div><a href="${link('servicio','vacuum')}" class="equipment-metric metric-vacuum"><h3>Vacuum</h3><strong>160</strong><span>barriles</span></a><a href="${link('servicio','frac-tanks')}" class="equipment-metric metric-tank"><h3>Frac tanks</h3><strong>500</strong><span>barriles</span></a><div class="steam-explanation"><h3>Circuito de vapor</h3><p>Generación y distribución de vapor para calentamiento y procesos, independiente del manejo de crudo.</p><a href="${link('servicio','calderas-portatiles')}">Vapor a proceso ${icon('arrow')}</a><span>Agua de alimentación ${icon('arrow')}</span></div><small class="art-note">Representación ilustrativa de equipos y procesos.</small>`,{network:'equipment',exit:.65})
 const home=()=>hero('Experiencia<br>que mueve<br><em>tu operación.</em>','Vapor, recuperación de crudo <br>y automatización para una operación <br>más segura y eficiente.',undefined,btn('Explorar servicios',link('servicios'))+btn('Contactar',link('contacto'),true),'home-hero')+history()+categories()+equipment()+control()+work()+areas()+close()
 const presence=()=>scene('gallery-presence',`<div class="presence-copy">${heading('Desde Zulia,<br><em>para el trabajo en campo.</em>','Operamos en las principales áreas de la industria petrolera, llevando soluciones adaptadas a cada entorno de trabajo.')}<p class="presence-location">${icon('pin')}<span>San Francisco<br>Zulia, Venezuela.</span></p></div><figure class="presence-plan">${image(asset('zulia-presence'),'Ilustración de pozos, estaciones, patios, fosas y plantas conectados')}<span class="plan-label plan-wells">Pozos</span><span class="plan-label plan-stations">Estaciones</span><span class="plan-label plan-yards">Patios</span><span class="plan-label plan-plants">Plantas</span><span class="plan-label plan-pits">Fosas</span></figure>`,{exit:.93})
 const about=()=>hero('<span class="about-year">1990</span>Una historia<br><em>hecha en campo.</em>','Vapor, recuperación de crudo y automatización al servicio de la industria petrolera venezolana.',undefined,'','about-gallery-hero')+scene('gallery-company split',`<div>${heading('Somos Service Petroleum<br>and Supply C.A.')}<p>Empresa venezolana de servicios petroleros con base en San Francisco, estado Zulia. Nos especializamos en recuperación de crudo, vapor, manejo y saneamiento de fluidos, soporte industrial y automatización.</p><p>Acompañamos las necesidades de campo con equipos y experiencia en pozos, estaciones, patios de tanques, fosas y plantas industriales.</p><p class="company-location">${icon('pin')} San Francisco, Zulia, Venezuela.</p></div>${photo(field('frac-tanks-modern-01.jpg'),'Infraestructura para la operación en campo')}`,{id:'next-scene',exit:.93})+categories('photo')+scene('gallery-fleet',`${heading('Equipos y conocimiento<br><em>de la operación.</em>','La experiencia se conoce a través de los equipos y del trabajo en campo.')}<div class="photo-pair">${photo(field('bajo-grande-caldera.jpg'),'Caldera portátil · Bajo Grande')}${photo(field('frac-tanks-modern-01.jpg'),'Frac tanks · Patio SPS')}</div>`,{exit:.08})+presence()+work('Soluciones reales<br><em>en campo.</em>')+close('Hablemos<br><em>de tu operación.</em>')
 const catalogue=()=>hero('Capacidad técnica.<br><em>Servicios conectados.</em>','Soluciones integrales en vapor, manejo de fluidos y automatización para tu operación.',undefined,btn('Nuestros servicios','#next-scene'),'catalogue-hero')+categories('strip').replace('<section ','<section id="next-scene" ')+groups.map((g,i)=>scene(`gallery-service-chapter ${i%2?'photo-left':''}`,`<div class="chapter-copy">${heading(g.title,g.intro)}${serviceList(services.filter(s=>s.group===g.id))}</div>${photo(i===2?asset('console-process'):i===1?field('frac-tanks-modern-01.jpg'):g.image,i===2?'Instrumentación y control · Ilustración':g.caption,'chapter-photo')}`,{id:g.id,exit:i%2?.93:.07})).join('')+close('¿Qué necesita<br><em>tu operación?</em>')
 const portfolio=()=>scene('portfolio-heading',`${heading('Proyectos','El trabajo se demuestra en campo.','h1')}${filters(groups.map(g=>[g.id,g.name]))}`,{exit:.93})+`<div class="directory" id="next-scene">${projects.map((p,i)=>scene(`gallery-project-row ${i%2?'text-first':'photo-first'}`,`${photo(p.photos[0],p.captions[0])}<div>${heading(p.name,p.title)}<p>${p.intro}</p>${textLink('Ver proyecto',link('proyecto',p.id))}</div>`,{exit:i%2?.93:.07}).replace('<section ','<section data-filter-item data-category="'+p.group+'" ')).join('')}</div><p class="filter-empty" hidden>No hay proyectos en esta categoría.</p>`+close('Hablemos de tu<br><em>próximo trabajo.</em>')
 const editorial=()=>hero('Conocimiento<br>que conecta<br><em>con el campo.</em>','Artículos técnicos sobre vapor, manejo de fluidos, automatización y equipos.',undefined,filters([...new Set(articles.map(a=>a.category))].map(c=>[c,c])),'editorial-hero')+`<div class="directory" id="next-scene">${articles.map((a,i)=>scene(`gallery-article-row ${i%2?'photo-first':'text-first'}`,`<div>${heading(a.title,a.intro)}${textLink('Leer artículo',link('articulo',a.id))}</div>${photo(a.image,a.illustration?'Ilustración conceptual':a.title)}`,{exit:i%2?.93:.07}).replace('<section ','<section data-filter-item data-category="'+a.category+'" ')).join('')}</div><p class="filter-empty" hidden>No hay artículos en esta categoría.</p>`+close('Hablemos<br><em>de tu operación.</em>')
 const serviceDetail=s=>{const p=projects.find(p=>p.id===s.project),isBoiler=s.id==='calderas-portatiles',related=services.filter(x=>x.group===s.group&&x.id!==s.id).slice(0,3);return hero(esc(s.title),s.headline,s.photo,btn('Consultar este servicio',link('contacto')+'&servicio='+s.id),'detail-hero',crumb('servicios',s.title))+
 scene('gallery-service-function split',`<div>${heading(isBoiler?'El equipo y su función':s.headline)}<p>${s.description}</p>${isBoiler?'<p>La caldera transfiere calor al agua para generar vapor. El vapor se utiliza como servicio térmico en distintas aplicaciones de campo. El circuito de agua y vapor es independiente del fluido que se necesita calentar.</p>':''}</div><figure>${image(isBoiler?asset('boiler-cutaway'):s.group==='automatizacion'?asset('console-process'):s.photo,isBoiler?'Esquema conceptual de transferencia de calor en una caldera':s.title)}${isBoiler?'<figcaption>Vista ilustrativa del equipo. No representa una instalación específica.</figcaption>':''}</figure>`,{id:'next-scene',exit:.07})+
 scene('gallery-applications',`${heading('Aplicaciones en campo','El servicio se adapta a las necesidades de la instalación.')}<div class="application-pictures">${s.applications.map((a,i)=>`<div data-pipe-port>${image(i===0?s.photo:i===1?field('frac-tanks-modern-01.jpg'):field('boscan-fosa-03.jpg'),'Portafolio SPS · Área de aplicación')}<div><h3>${a}</h3><p>${s.description}</p></div></div>`).join('')}</div>`,{exit:.93})+
 scene('gallery-planning',`${heading('Planificar el servicio','Para orientar la consulta es útil contar con estos datos.')}<div class="planning-grid">${s.questions.map((x,i)=>`<div>${icon(['pin','steam','gear'][i])}<h3>${x}</h3><p>Comparte la información disponible sobre las condiciones de tu operación.</p></div>`).join('')}</div>`,{exit:.07})+
 scene('project-gallery gallery-service-photos',`${heading('Equipos en operación','Fotografías del portafolio SPS.')}<div class="gallery-grid">${p.photos.slice(0,3).map((src,i)=>`<button class="gallery-open" data-full-image="${src}" data-caption="${esc(p.captions[i])}" aria-label="Ampliar ${esc(p.captions[i])}">${image(src,p.captions[i])}<span>${p.captions[i]} ${icon('arrow')}</span></button>`).join('')}</div>`,{exit:.93})+
 scene('gallery-related-project',`${heading('Proyecto relacionado')}<div class="related-project-inner">${photo(p.photos[0],p.captions[0])}<div>${heading(p.name,p.title)}${textLink('Ver proyecto',link('proyecto',p.id))}</div></div>`,{exit:.07})+close('¿Necesitas este servicio<br><em>en tu operación?</em>')+scene('gallery-related-services',`${heading('Otros servicios relacionados')}<div class="small-service-cards">${related.map(x=>`<a href="${link('servicio',x.id)}">${image(x.photo,x.title)}<h3>${x.title}</h3>${icon('arrow')}</a>`).join('')}</div>`,{exit:.93})}
 const projectDetail=p=>hero(`${esc(p.name)}<br><em>${esc(p.title)}</em>`,'Vapor, equipos y servicios en campo.',p.photos[0],`<dl class="hero-facts"><div><dt>Ubicación</dt><dd>${p.location}</dd></div><div><dt>Servicio</dt><dd>${p.title}</dd></div></dl>`,'detail-hero project-gallery-hero',crumb('proyectos',p.name))+
 scene('gallery-project-story split',`<div>${heading('El trabajo')}<p><strong>${p.intro}</strong></p><p>${p.body}</p></div>${photo(p.photos[1]||p.photos[0],p.captions[1]||p.captions[0])}`,{id:'next-scene',exit:.93})+
 scene('gallery-operation',`${heading('La operación, conectada','Esquema conceptual de los equipos y conexiones de proceso.')}<figure>${image(p.group==='vapor'?asset('project-operation'):p.photos[0],p.group==='vapor'?'Ilustración conceptual de caldera, línea de vapor y recuperación':p.captions[0])}<figcaption>Esquema ilustrativo. Las fotografías documentales se muestran en el registro siguiente.</figcaption></figure>${p.group==='vapor'?`<div class="process-labels"><span>Caldera portátil<br><b>Generación de vapor</b></span><span>Líneas de distribución<br><b>Servicio térmico</b></span><span>Aplicación en campo<br><b>Recuperación</b></span></div>`:''}`,{exit:.07})+
 scene('project-gallery',`${heading('Registro fotográfico','Equipo, conexiones y área de trabajo.')}<div class="gallery-grid">${p.photos.map((src,i)=>`<button class="gallery-open" data-full-image="${src}" data-caption="${esc(p.captions[i])}" aria-label="Ampliar ${esc(p.captions[i])}">${image(src,p.captions[i])}<span>${p.captions[i]}${icon('arrow')}</span></button>`).join('')}</div>`,{exit:.93})+
 scene('gallery-related-services',`${heading('Equipos y servicios relacionados')}<div class="small-service-cards">${p.services.map(sid=>services.find(s=>s.id===sid)).map(s=>`<a href="${link('servicio',s.id)}" data-pipe-port>${image(s.photo,s.title)}<h3>${s.title}</h3>${icon('arrow')}</a>`).join('')}</div>`,{exit:.07})+work('Más trabajos<br><em>en campo.</em>')+close('¿Tu operación necesita<br><em>un servicio similar?</em>')
 const articleDetail=a=>hero(esc(a.title),a.intro,a.category==='Automatización'?asset('sensor-assembly'):a.image,'','article-hero gallery-reading-hero',crumb('articulos',a.category))+
 scene('gallery-reading',`<aside class="article-index"><h3>Contenido<br>del artículo</h3><nav aria-label="Contenido del artículo">${a.sections.map(([t],i)=>`<a href="#lectura-${i}">${i+1}. ${t}</a>`).join('')}${a.category==='Automatización'?'<a href="#panel-control">Instrumentación, control y supervisión</a>':''}<a href="#related-article">Servicios relacionados</a></nav></aside><div class="article-body">${a.sections.map(([t,text],i)=>`<article id="lectura-${i}"><div><h2>${i+1}. ${t}</h2><p>${text}</p></div>${i<2?photo(i===0?field('bajo-grande-caldera.jpg'):field('frac-tanks-modern-01.jpg'),i===0?'Caldera · Portafolio SPS':'Frac tanks · Portafolio SPS'):''}</article>${i===1&&a.category==='Automatización'?`<figure class="article-process" id="panel-control"><h2>Del instrumento al SCADA</h2><div>${image(asset('sensor-assembly'),'Instrumento de campo')}${image(asset('console-process'),'PLC y pantalla SCADA · Ilustración conceptual')}</div><figcaption>Instrumento → Señal de datos → PLC / RTU → SCADA · Vista ilustrativa</figcaption></figure><div class="definition-strip">${[['Instrumentación','Dispositivos que miden variables del proceso y las convierten en señales.'],['Control','Equipos que reciben las señales, las procesan y ejecutan la lógica de control.'],['Supervisión','Sistemas que visualizan la información y facilitan el seguimiento.']].map(([h,p])=>`<div><h3>${h}</h3><p>${p}</p></div>`).join('')}</div>`:''}`).join('')}</div>`,{network:'reading',id:'next-scene',exit:.93})+
 scene('article-resources',`<div><h2>Servicios relacionados</h2>${serviceList(a.related.map(id=>services.find(s=>s.id===id)))}</div><div><h2>Artículos relacionados</h2>${articles.filter(x=>x.id!==a.id).slice(0,2).map(x=>textLink(x.title,link('articulo',x.id))).join('')}</div><div><h2>Hablemos de tu proyecto</h2><p>Conversemos sobre las necesidades de tu operación.</p>${phoneCard()}</div>`,{id:'related-article',exit:.07})
 return {home,about,catalogue,portfolio,editorial,serviceDetail,projectDetail,articleDetail,close}
}
