const arrow='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>'
const image=(file,caption='',enhanced=false)=>`<figure><img src="${enhanced?'../v3-fotos-reales/':'/assets/sps-field/'}${file}" alt="${caption}" loading="eager">${caption?`<figcaption>${caption}</figcaption>`:''}</figure>`
const link=(text,id,kind='text-link')=>`<a class="${kind}" href="?vista=${id}">${text}${arrow}</a>`
const groups=[
{id:'vapor',name:'Vapor y recuperación',title:'Vapor y recuperación de crudo.',image:'bajo-grande-caldera.jpg',caption:'Caldera portátil · Bajo Grande',intro:'Servicios de vapor para pozos, fosas, patios de tanques, calentamiento de crudo y recuperación de hidrocarburos.',items:['Alquiler de calderas portátiles','Inyección de vapor a pozos','Inyección de vapor para patio de tanques','Calentamiento de crudo en Pit','Recuperación de crudo en fosas de pasivos ambientales','Calentamiento de sellos de bomba para carga de buques','Reparación y mantenimiento de calentadores','Reparación y mantenimiento de calderas']},
{id:'manejo',name:'Manejo y saneamiento',title:'Manejo y saneamiento de hidrocarburos.',image:'boscan-slop-antes.jpg',caption:'Recuperación de crudo · Campo Boscán',intro:'Tratamiento, saneamiento y disposición temporal de hidrocarburos, aguas de proceso, lodos y sedimentos petrolizados.',items:['Saneamiento mediante hidrojet en áreas contaminadas con petróleo','Bombeo de crudo','Trasegado con vacuum de 160 barriles','Alquiler de Frac Tank con capacidad de 500 barriles','Camiones con equipos de soldadura','Disposición temporal de desechos provenientes de derrames']},
{id:'automatizacion',name:'Automatización y control',title:'Automatización, control y telemetría.',image:'bajo-grande-patio-04.jpg',caption:'Equipos en campo · Bajo Grande',intro:'Integración de instrumentación, control y comunicaciones para pozos, estaciones y plantas industriales.',items:['Rehabilitación de telemetría de pozos y estaciones','Programación de PLC en estaciones','Programación de RTU para pozos de producción e inyección de agua','Servicio SCADA Wonderware CIBO','Variadores de pozos con bombas BCP y sus RTU','Instrumentación de pozos y estaciones','Sistemas de puesta a tierra y protección de pararrayos','Paneles solares para telemetría en pozos sin electricidad']}
]
const projects=[
['boscan-slop-antes.jpg','Calentamiento y recuperación de crudo Slop','Campo Boscán · Estación 1','Recuperación de crudo con vapor en fosas, con registro fotográfico de la intervención.'],
['tia-juana-b5-01.jpg','Inyección de vapor a pozos','PDVSA Tía Juana · Estación B5','Operación con equipos movilizados en estación y áreas de producción.'],
['bajo-grande-caldera.jpg','Calentamiento de crudo en Pit','PDVSA Bajo Grande','Instalación de caldera, tanques, líneas y sistemas auxiliares para el manejo de crudo.'],
['boscan-fosa-03.jpg','Saneamiento por derrames','San Francisco–La Cañada','Saneamiento y disposición temporal de desechos en áreas afectadas por hidrocarburos.'],
['frac-tanks-modern-01.jpg','Almacenamiento temporal','Patio SPS · Frac tanks','Tanques con estructuras, escaleras y conexiones para operaciones petroleras.'],
['bajo-grande-patio-04.jpg','Automatización e instrumentación','Estaciones y plantas industriales','Soporte en telemetría, RTU, PLC, instrumentación, puesta a tierra y comunicación.']
]
const screens=[
{id:'inicio',label:'Inicio',nav:'inicio',html:`<section class="screen hero"><div class="hero-top"><h1>Experiencia de campo.<br><span>Respaldo para tu operación.</span></h1><div class="hero-copy"><p>Vapor, recuperación de crudo, saneamiento y automatización. Soluciones petroleras e industriales con equipos movilizados en campo.</p>${link('Descubre nuestros servicios','servicios')}</div></div><div class="hero-photo" style="position:relative"><img src="../v3-fotos-reales/panorama-mejorada.png" alt="Patio operativo SPS con tanques, tuberías y caldera portátil"><div class="hero-caption"><strong>En campo desde 1990</strong><span>Service Petroleum<br>and Supply C.A.</span></div></div><div class="hero-end"><span>Capacidad técnica. Experiencia operativa.</span><span>Zulia, Venezuela</span></div></section>`},
{id:'nosotros',label:'Empresa y trayectoria',nav:'nosotros',html:`<section class="screen"><div class="split photo-big">${image('caldera-mejorada.png','Equipos SPS · Bajo Grande',true)}<div class="copy-stack"><h1>Una trayectoria construida en campo.</h1><p>Service Petroleum and Supply C.A. es una empresa venezolana enfocada en servicios petroleros, recuperación de crudo, vapor, automatización y soporte industrial.</p><p>Trabajamos en pozos, estaciones, patios de tanques, fosas y plantas industriales, con personal técnico, equipos y criterio operativo.</p>${link('Conoce nuestras capacidades','servicios')}</div></div><div class="timeline">${[['1990','Fundación en Maracaibo'],['2000','Instrumentación y automatización'],['2010','Crecimiento y equipos propios'],['2020','Control de procesos y saneamiento'],['Hoy','Experiencia al servicio de tu operación']].map(([year,text])=>`<div><strong>${year}</strong><span>${text}</span></div>`).join('')}</div></section>`},
{id:'servicios',label:'Líneas de servicio',nav:'servicios',html:`<section class="screen"><div class="section-head"><h1>Una respuesta para<br>cada operación.</h1><p>Tres líneas de servicio que reúnen la capacidad técnica y operativa de SPS.</p></div><div class="service-grid">${groups.map(g=>`<article class="service-tile">${image(g.image)}<h3>${g.title}</h3><p>${g.intro}</p>${link('Explorar servicios',g.id)}</article>`).join('')}</div></section>`},
...groups.map(g=>({id:g.id,label:g.name,nav:'servicios',html:`<section class="screen"><div class="section-head"><h1>${g.title}</h1></div><nav class="subnav" aria-label="Categorías de servicios">${groups.map(item=>`<a class="${item.id===g.id?'selected':''}" href="?vista=${item.id}">${item.name}</a>`).join('')}<a href="?vista=equipos">Equipos de campo</a></nav><div class="detail-layout">${image(g.image,g.caption)}<div class="detail-content"><p>${g.intro}</p><ul class="service-list">${g.items.map(item=>`<li>${arrow}<span>${item}</span></li>`).join('')}</ul>${link('Consultar este servicio','contacto','button')}</div></div></section>`})),
{id:'equipos',label:'Equipos de campo',nav:'servicios',html:`<section class="screen"><div class="section-head"><h1>Equipos preparados<br>para el campo.</h1><p>Unidades, tanques y accesorios para el almacenamiento temporal y las operaciones petroleras.</p></div><div class="equipment">${image('frac-tanks-modern-01.jpg','Frac tanks · Patio SPS')}<div class="equipment-list"><div class="equipment-item"><h3>Calderas portátiles</h3><p>Vapor para pozos, calentamiento de crudo y patios de tanques.</p></div><div class="equipment-item"><h3>Frac tanks</h3><strong>Capacidad de 500 barriles</strong><p>Almacenamiento temporal en operaciones de campo.</p></div><div class="equipment-item"><h3>Unidades vacuum</h3><strong>Capacidad de 160 barriles</strong><p>Trasegado y manejo de hidrocarburos.</p></div>${link('Consultar disponibilidad','contacto')}</div></div></section>`},
...[0,1].map((page)=>({id:page?'proyectos-mas':'proyectos',label:page?'Más trabajos realizados':'Trabajos realizados',nav:'proyectos',html:`<section class="screen"><div class="section-head"><h1>${page?'Capacidad en distintos<br>frentes de trabajo.':'La experiencia se demuestra<br>en cada proyecto.'}</h1><p>Trabajos petroleros e industriales documentados en campo.</p></div><div class="project-tabs"><a class="${page?'':'selected'}" href="?vista=proyectos">Vapor y recuperación</a><a class="${page?'selected':''}" href="?vista=proyectos-mas">Saneamiento, equipos y control</a></div><div class="project-grid">${projects.slice(page*3,page*3+3).map(([img,title,location,description])=>`<article class="project">${image(img)}<h3>${title}</h3><div class="location">${location}</div><p>${description}</p></article>`).join('')}</div></section>`})),
{id:'areas',label:'Áreas y ubicaciones',nav:'areas',html:`<section class="screen"><div class="section-head"><h1>Donde tu operación<br>nos necesita.</h1><p>Experiencia en entornos petroleros e industriales, desde nuestra base en Zulia.</p></div><div class="area-layout"><div class="area-list">${[['Pozos de producción','Inyección de vapor, instrumentación y telemetría.'],['Estaciones','Control, automatización y soporte a equipos.'],['Patios de tanques','Calentamiento y manejo de crudo.'],['Fosas y pasivos ambientales','Recuperación de crudo y saneamiento.'],['Plantas industriales','Instrumentación y control de procesos.'],['Áreas de derrames','Saneamiento y disposición temporal de desechos.']].map(([title,copy])=>`<div class="area-item"><h3>${title}</h3><p>${copy}</p></div>`).join('')}</div><aside class="locations"><h3>Desde San Francisco, Zulia.</h3><p>Ubicaciones con trabajos documentados en el portafolio de SPS:</p><ul><li>Campo Boscán · Estación 1</li><li>Tía Juana · Estación B5</li><li>PDVSA Bajo Grande</li><li>San Francisco–La Cañada</li></ul>${link('Consultar mi ubicación','contacto')}</aside></div></section>`},
{id:'respaldo',label:'Nuestro respaldo',nav:'nosotros',html:`<section class="screen"><div class="section-head"><h1>El respaldo detrás<br>de cada servicio.</h1><p>Una forma de trabajar que combina capacidad técnica, seguridad y responsabilidad.</p></div><div class="values-layout">${image('patio-vapor-02.jpg','Equipos SPS en campo')}<div>${[['Personal técnico','Experiencia en vapor, instrumentación, automatización y manejo de hidrocarburos.'],['Equipos propios','Calderas, tanques, unidades móviles y herramientas para la operación.'],['Seguridad industrial','Seguridad y protección ambiental como condiciones de trabajo.'],['Evidencia de campo','Registro fotográfico y documentación de las operaciones realizadas.']].map(([title,copy])=>`<div class="value-row"><h3>${title}</h3><p>${copy}</p></div>`).join('')}</div></div></section>`},
{id:'contacto',label:'Contacto',nav:'contacto',html:`<section class="screen"><div class="section-head"><h1>Hablemos de tu<br>próxima operación.</h1><p>Indica el servicio, la ubicación y la urgencia para orientar la respuesta técnica.</p></div><div class="contact-layout"><div class="contact-details"><a href="tel:+582613226494">0261 322 6494</a><a href="tel:+584146361373">+58 414 636 1373</a><address>Av. 5, Calle 13, N.º 26A-162<br>San Francisco, Maracaibo<br>Zulia, Venezuela</address>${image('bajo-grande-caldera.jpg')}</div><form class="contact-form" id="request-form"><label class="field">Nombre<input name="nombre" autocomplete="name" required placeholder="Tu nombre"></label><label class="field">Empresa<input name="empresa" autocomplete="organization" placeholder="Nombre de la empresa"></label><label class="field">Teléfono<input name="telefono" type="tel" autocomplete="tel" placeholder="Número de contacto"></label><label class="field">Correo<input name="correo" type="email" autocomplete="email" placeholder="Tu correo electrónico"></label><label class="field">Servicio requerido<select name="servicio"><option>Seleccionar servicio</option>${groups.map(g=>`<option>${g.name}</option>`).join('')}<option>Equipos de campo</option></select></label><label class="field">Ubicación del trabajo<input name="ubicacion" placeholder="Campo, ciudad o instalación"></label><label class="field wide">Urgencia<select name="urgencia"><option>Solicitar cotización</option><option>Programar visita técnica</option><option>Atención inmediata</option><option>Consulta general</option></select></label><label class="field wide">Descripción del trabajo<textarea name="descripcion" rows="2" required placeholder="Cuéntanos qué necesita tu operación"></textarea></label><div class="form-foot"><button class="button" type="submit">Preparar solicitud ${arrow}</button><p id="form-status" role="status">Prepara un resumen para compartirlo con el equipo de SPS.</p></div></form></div></section>`}
]
const requested=new URLSearchParams(location.search).get('vista')||'inicio'
const index=Math.max(0,screens.findIndex(s=>s.id===requested))
const current=screens[index]
document.getElementById('content').innerHTML=current.html
document.title=`SPS · ${current.label}`
document.getElementById('screen-name').textContent=current.label
document.getElementById('previous').href=`?vista=${screens[(index+screens.length-1)%screens.length].id}`
document.getElementById('next').href=`?vista=${screens[(index+1)%screens.length].id}`
document.querySelector(`[data-section="${current.nav}"]`)?.setAttribute('aria-current','page')
document.getElementById('request-form')?.addEventListener('submit',event=>{event.preventDefault();const values=new FormData(event.currentTarget);const text='Solicitud de servicio SPS\n\n'+[...values].map(([name,value])=>name+': '+value).join('\n');const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='solicitud-sps.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('form-status').textContent='Resumen descargado. Todavía no se ha enviado a SPS.'})
