export const groups=[
{id:'vapor',name:'Vapor y recuperación',title:'Vapor y recuperación de crudo.',image:'bajo-grande-caldera.jpg',caption:'Caldera portátil · Bajo Grande',intro:'Servicios de vapor para pozos, fosas, patios de tanques, calentamiento de crudo y recuperación de hidrocarburos.',items:['Alquiler de calderas portátiles','Inyección de vapor a pozos','Inyección de vapor para patio de tanques','Calentamiento de crudo en Pit','Recuperación de crudo en fosas de pasivos ambientales','Calentamiento de sellos de bomba para carga de buques','Reparación y mantenimiento de calentadores','Reparación y mantenimiento de calderas']},
{id:'manejo',name:'Manejo y saneamiento',title:'Manejo y saneamiento de hidrocarburos.',image:'boscan-slop-antes.jpg',caption:'Recuperación de crudo · Campo Boscán',intro:'Tratamiento, saneamiento y disposición temporal de hidrocarburos, aguas de proceso, lodos y sedimentos petrolizados.',items:['Saneamiento mediante hidrojet en áreas contaminadas con petróleo','Bombeo de crudo','Trasegado con vacuum de 160 barriles','Alquiler de Frac Tank con capacidad de 500 barriles','Camiones con equipos de soldadura','Disposición temporal de desechos provenientes de derrames']},
{id:'automatizacion',name:'Automatización y control',title:'Automatización, control y telemetría.',image:'bajo-grande-patio-04.jpg',caption:'Equipos en campo · Bajo Grande',intro:'Integración de instrumentación, control y comunicaciones para pozos, estaciones y plantas industriales.',items:['Rehabilitación de telemetría de pozos y estaciones','Programación de PLC en estaciones','Programación de RTU para pozos de producción e inyección de agua','Servicio SCADA Wonderware CIBO','Variadores de pozos con bombas BCP y sus RTU','Instrumentación de pozos y estaciones','Sistemas de puesta a tierra y protección de pararrayos','Paneles solares para telemetría en pozos sin electricidad']}
]
export const projects=[
['boscan-slop-antes.jpg','Calentamiento y recuperación de crudo Slop','Campo Boscán · Estación 1','Recuperación de crudo con vapor en fosas, con registro fotográfico de la intervención.'],
['tia-juana-b5-01.jpg','Inyección de vapor a pozos','PDVSA Tía Juana · Estación B5','Operación con equipos movilizados en estación y áreas de producción.'],
['bajo-grande-caldera.jpg','Calentamiento de crudo en Pit','PDVSA Bajo Grande','Instalación de caldera, tanques, líneas y sistemas auxiliares para el manejo de crudo.'],
['boscan-fosa-03.jpg','Saneamiento por derrames','San Francisco–La Cañada','Saneamiento y disposición temporal de desechos en áreas afectadas por hidrocarburos.'],
['frac-tanks-modern-01.jpg','Almacenamiento temporal','Patio SPS · Frac tanks','Tanques con estructuras, escaleras y conexiones para operaciones petroleras.'],
['bajo-grande-patio-04.jpg','Automatización e instrumentación','Estaciones y plantas industriales','Soporte en telemetría, RTU, PLC, instrumentación, puesta a tierra y comunicación.']
]

