import { groups, projects } from './data.js'
const arrow='<svg class="arrow-icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 18 18 6M6 6h12v12"/></svg>'
const url=(page,section=0)=>`?pagina=${page}&seccion=${section}`
const link=(label,page,section=0,cls='text-link')=>`<a class="${cls}" href="${url(page,section)}">${label}${arrow}</a>`
const img=(name,caption='',enhanced=false)=>`<figure class="photo"><img src="${enhanced?'../v3-fotos-reales/':'/assets/sps-field/'}${name}" alt="${caption||'Equipos y operaciones de SPS en campo'}">${caption?`<figcaption>${caption}</figcaption>`:''}</figure>`
const heading=(title,copy='',cls='')=>`<div class="section-top ${cls}"><h1>${title}</h1>${copy?`<p>${copy}</p>`:''}</div>`
const screen=(html,cls='')=>`<section class="screen ${cls}">${html}</section>`
const footer=()=>`<div class="footer-info"><div><h3>Service Petroleum and Supply C.A.</h3><p>Servicios petroleros, recuperación de crudo, vapor, saneamiento, automatización y soporte industrial.</p></div><div><h3>Contacto directo</h3><p><a href="tel:+582613226494">0261 322 6494</a><br><a href="tel:+584146361373">+58 414 636 1373</a></p></div><div><h3>San Francisco, Zulia</h3><p>Av. 5, Calle 13, N.º 26A-162<br>San Francisco, Maracaibo, Venezuela.</p></div></div>`
const intro='Service Petroleum and Supply C.A. es una empresa venezolana enfocada en servicios petroleros, recuperación de crudo, vapor, automatización y soporte industrial.'
const serviceCopy=[
['Equipos móviles para los servicios de vapor en campo.','Aplicación de vapor en pozos de producción.','Servicio de vapor para operaciones en patios de almacenamiento.','Calentamiento de crudo en áreas de manejo y transferencia.','Aplicación de vapor para recuperar hidrocarburos en fosas.','Calentamiento de sellos durante las operaciones de carga.','Intervenciones de reparación y mantenimiento de calentadores.','Intervenciones de reparación y mantenimiento de calderas.'],
['Limpieza mediante hidrojet en superficies y áreas afectadas.','Servicio de bombeo para el manejo de hidrocarburos.','Trasegado de fluidos con unidades de la capacidad indicada.','Tanques para almacenamiento temporal en campo.','Unidades con equipos de soldadura para soporte operativo.','Manejo temporal de desechos procedentes de áreas afectadas.'],
['Recuperación de los sistemas de telemetría de campo.','Programación de controladores para estaciones industriales.','Configuración de unidades remotas en pozos de producción e inyección.','Soporte para supervisión y control de procesos.','Atención a variadores y control remoto de pozos con bombas BCP.','Instrumentación asociada a los procesos de campo.','Sistemas de tierra y protección eléctrica de instalaciones.','Alimentación solar de telemetría en sitios sin electricidad.']
]
const history=[['1990','Fundación de la empresa','SPS nace en Maracaibo para prestar servicios de vapor, calderas y mantenimiento mecánico a la industria petrolera.'],['2000','Instrumentación y automatización','Se incorporan servicios de instrumentación, medición y control de procesos en campos y estaciones.'],['2010','Crecimiento y equipos propios','La capacidad se amplía con calderas portátiles, tanques y unidades de servicio móvil.'],['2020','Control y saneamiento','Se integran SCADA, PLC, RTU e intervenciones de saneamiento industrial.'],['Hoy','Presente operacional','Equipos y personal técnico para distintos frentes de trabajo de la industria.']]
const areas=[['Pozos de producción','Inyección de vapor, instrumentación y telemetría para instalaciones de producción.'],['Estaciones','Programación de controladores, monitoreo de variables y comunicaciones de campo.'],['Patios de tanques','Calentamiento de crudo, manejo de fluidos y apoyo en operaciones de almacenamiento.'],['Fosas y pasivos ambientales','Recuperación de crudo con vapor y atención de áreas con hidrocarburos.'],['Plantas industriales','Instrumentación, automatización y control de procesos industriales.'],['Áreas afectadas por derrames','Saneamiento y disposición temporal de desechos provenientes de la intervención.']]
const values=[['Seguridad industrial','La seguridad es una condición de trabajo en cada intervención y en el manejo de los equipos.'],['Mejora continua','Mejora de equipos, procesos y preparación del personal para responder a las condiciones operativas.'],['Coordinación','Trabajo conjunto con clientes y empresas aliadas para organizar las actividades en campo.'],['Responsabilidad ambiental','Respeto por el ambiente en las operaciones con hidrocarburos y en el saneamiento de áreas afectadas.'],['Respuesta de campo','Movilización y soporte técnico ante requerimientos en pozos, estaciones e instalaciones.'],['Evidencia del trabajo','Registro fotográfico y documentación técnica de las operaciones realizadas.']]
const secondImages=['boscan-slop-despues.jpg','tia-juana-b5-02.jpg','bajo-grande-patio-02.jpg','boscan-fosa-04.jpg','frac-tanks-modern-02.jpg','frac-tank-line-02.jpg']
const projectDetails=[
{scope:['Calentamiento y recuperación de crudo Slop.','Aplicación de vapor en fosas.','Registro fotográfico antes y después.'],copy:'Las fotografías del proyecto muestran la fosa y las instalaciones utilizadas durante la recuperación de crudo. El portafolio conserva dos momentos de la intervención para consultar su evolución visual.',service:'Vapor y recuperación de crudo',group:1},
{scope:['Inyección de vapor en pozos.','Movilización de equipos a la estación.','Atención en áreas de producción.'],copy:'El trabajo documentado corresponde a la estación B5 de Tía Juana. Las imágenes permiten reconocer la locación y las áreas en las que se desarrolló la operación de inyección de vapor.',service:'Vapor y recuperación de crudo',group:1},
{scope:['Instalación de caldera y líneas.','Tanques y sistemas auxiliares.','Calentamiento y manejo de crudo.'],copy:'La intervención reúne caldera portátil, tanques, líneas y sistemas auxiliares para el calentamiento de crudo en Pit y patio de tanques. Las fotografías muestran la disposición de los equipos en Bajo Grande.',service:'Vapor y recuperación de crudo',group:1},
{scope:['Saneamiento de áreas afectadas.','Atención de desechos de hidrocarburos.','Disposición temporal del material.'],copy:'El portafolio incluye trabajos de saneamiento en las costas de San Francisco–La Cañada. El registro presenta las áreas de trabajo vinculadas al manejo de desechos provenientes de derrames.',service:'Manejo y saneamiento',group:2},
{scope:['Almacenamiento temporal de fluidos.','Estructuras, escaleras y conexiones.','Equipos para operaciones petroleras.'],copy:'Los frac tanks del patio SPS forman parte de la capacidad de almacenamiento temporal. Las fotografías permiten revisar sus estructuras, escaleras y puntos de conexión para operaciones en campo.',service:'Equipos y almacenamiento',group:4},
{scope:['Telemetría, RTU y PLC.','Instrumentación y puesta a tierra.','Comunicación entre campo y control.'],copy:'SPS presta soporte en automatización e instrumentación de estaciones y plantas industriales. Esta línea integra señales de campo, controladores y comunicaciones para la supervisión de procesos.',service:'Automatización y control',group:3}
]
export const pages=[
{id:'inicio',name:'Inicio',sections:[
{name:'Presentación',html:screen(`<h1>Servicios petroleros<br><span class="blue">con experiencia de campo</span><span class="red-dot">.</span></h1><div class="hero-stage"><img src="/assets/sps-field/bajo-grande-caldera.jpg" alt="Panorámica del patio operativo SPS"><div class="hero-text"><p>SPS integra servicios de vapor, recuperación de crudo, saneamiento y automatización industrial. Llevamos equipos y capacidad técnica a pozos, estaciones, patios de tanques y plantas industriales.</p><div class="actions">${link('Conocer nuestros servicios','servicios',0,'button')}</div>${link('Ver trabajos realizados','proyectos')}</div><div class="hero-note">Service Petroleum and Supply C.A.<strong>Desde 1990</strong></div></div>`,'hero')},
{name:'Quiénes somos',html:screen(`<div class="editorial"><div><h2>Una empresa preparada<br>para trabajar en campo.</h2><p>${intro}</p><p>La experiencia de SPS se desarrolla en instalaciones donde la respuesta técnica requiere equipos, personal y conocimiento de la operación. Atendemos trabajos de vapor, manejo de hidrocarburos, instrumentación y control de procesos.</p>${link('Conocer la empresa','nosotros')}</div><div class="overlap-photo">${img('bajo-grande-caldera.jpg')}<div class="insert">${img('tia-juana-b5-01.jpg')}</div><span class="date-stamp">1990</span></div></div><div class="intro-foot"><article><h3>Personal técnico</h3><p>Experiencia en vapor, instrumentación, automatización y manejo de hidrocarburos.</p></article><article><h3>Equipos propios</h3><p>Calderas, tanques, unidades móviles y herramientas para resolver en sitio.</p></article><article><h3>Operaciones documentadas</h3><p>Fotografías y descripciones de trabajos realizados en distintos frentes.</p></article></div>`)},
{name:'Servicios',html:screen(`${heading('Servicios organizados<br>por necesidad operativa.','Explora las tres líneas de SPS. Cada una reúne actividades específicas que puedes consultar en el catálogo completo.')}<div id="service-explorer" class="service-explorer"></div>`)},
{name:'Equipos',html:screen(`${heading('Equipos para el manejo<br>y la recuperación de crudo.','La operación combina calderas portátiles, unidades vacuum, tanques y accesorios de campo según el trabajo requerido.')}<div class="equipment-stage">${img('frac-tanks-modern-01.jpg','Frac tanks del patio SPS')}<div class="equipment-notes"><article><h3>Calderas portátiles</h3><p>Servicio de vapor para pozos, patios de tanques, fosas y calentamiento de crudo.</p></article><article><h3>Vacuum y almacenamiento</h3><strong>Vacuum de 160 barriles · Frac tanks de 500 barriles</strong><p>Trasegado de fluidos y almacenamiento temporal en operaciones petroleras.</p></article>${link('Consultar equipos y servicios','servicios',4)}</div></div>`)},
{name:'Trabajos realizados',html:screen(`${heading('Trabajos realizados<br>en instalaciones petroleras.','El portafolio reúne fotografías y descripciones de seis intervenciones y capacidades de campo.')}<div class="featured-work"><div class="primary">${img('boscan-slop-antes.jpg')}<div class="work-caption"><div><h3>Campo Boscán</h3><p>Calentamiento y recuperación de crudo Slop en la Estación 1.</p></div>${link('Ver intervención','proyectos',1)}</div></div><div class="mini-work"><a href="${url('proyectos',2)}">${img('tia-juana-b5-01.jpg')}<h3>Inyección de vapor · Tía Juana</h3></a><a href="${url('proyectos',3)}">${img('bajo-grande-caldera.jpg')}<h3>Calentamiento de crudo · Bajo Grande</h3></a></div></div>`)},
{name:'Áreas de atención',html:screen(`${heading('Áreas de trabajo<br>y experiencia documentada.','SPS atiende necesidades técnicas en entornos petroleros e industriales desde San Francisco, estado Zulia.')}<div class="area-layout"><div class="area-grid">${areas.map(([name,copy])=>`<article><h3>${name}</h3><p>${copy}</p></article>`).join('')}</div><aside class="location-panel"><h3>Ubicaciones del portafolio</h3><p>Los trabajos publicados permiten conocer la experiencia de SPS en estas instalaciones y zonas.</p><ul class="place-list"><li>Campo Boscán · Estación 1</li><li>Tía Juana · Estación B5</li><li>PDVSA Bajo Grande</li><li>San Francisco–La Cañada</li><li>Patio SPS</li></ul>${link('Consultar mi ubicación','contacto')}</aside></div>`)},
{name:'Contacto y cierre',html:screen(`<div class="contact-banner"><div><h2>Cuéntanos qué necesita<br>tu operación.</h2><p>Indica el servicio, la ubicación del trabajo y la urgencia. Una descripción del área, del fluido o de los equipos permite orientar la conversación técnica.</p><p>Para servicios de vapor, saneamiento, tanques, mantenimiento, telemetría o automatización, puedes comunicarte directamente con SPS.</p><div class="actions">${link('Preparar solicitud','contacto',1,'button')}</div><div class="contact-lines"><a href="tel:+582613226494">0261 322 6494</a><a href="tel:+584146361373">+58 414 636 1373</a></div></div>${img('bajo-grande-patio-02.jpg')}</div>${footer()}`)}]},
{id:'nosotros',name:'Nosotros',sections:[
{name:'La empresa',html:screen(`<div class="about-mast"><h1>Service Petroleum<br>and Supply C.A.<span class="red-dot">.</span></h1><div><p>${intro}</p><p>Su trabajo se reconoce en pozos, estaciones, patios de tanques, fosas y plantas industriales: espacios donde cada intervención requiere equipos, personal y criterio operativo.</p></div></div><div class="history-photo history-numerals"><svg viewBox="0 0 1332 310" role="img" aria-labelledby="history-year-title"><title id="history-year-title">Desde 1990: instalaciones y equipos de SPS dentro de los números</title><defs><clipPath id="history-year-mask"><text x="0" y="305" textLength="1332" lengthAdjust="spacingAndGlyphs">1990</text><path d="M0 185H1080V270H1190V305H0Z"/></clipPath></defs><image href="/assets/sps-field/bajo-grande-caldera.jpg" width="1332" height="310" preserveAspectRatio="xMidYMid slice" clip-path="url(#history-year-mask)"/></svg></div><div class="intro-foot"><article><h3>Vapor e hidrocarburos</h3><p>Recuperación de crudo, calentamiento, manejo de fluidos y saneamiento industrial.</p></article><article><h3>Automatización</h3><p>Instrumentación, SCADA, PLC, RTU, telemetría y comunicaciones de campo.</p></article><article><h3>Base en Zulia</h3><p>San Francisco, Maracaibo. Contacto directo para necesidades de campo.</p></article></div>`)},
{name:'Historia y trayectoria',html:screen(`${heading('Una trayectoria que amplía<br>la capacidad de servicio.','Desde su fundación en 1990, SPS ha incorporado equipos y servicios para distintos frentes de la industria petrolera.')}<div class="history-photo"><img src="/assets/sps-field/frac-tank-line-01.jpg" alt="Equipos en el patio SPS"></div><div class="timeline">${history.map(([year,title,copy])=>`<article><strong>${year}</strong><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div>`)},
{name:'Misión y visión',html:screen(`<div class="purpose"><article><h2>Nuestra misión</h2><h3>Prestar servicios confiables en condiciones exigentes.</h3><p>Garantizar calidad, seguridad y continuidad operativa en servicios petroleros e industriales, con personal técnico preparado y mejora permanente del proceso.</p><p>El enfoque de SPS une conocimiento técnico y capacidad de campo para atender las necesidades del trabajo.</p></article><article><h2>Nuestra visión</h2><h3>Ser reconocidos por respuesta y excelencia operacional.</h3><p>Consolidarse como aliado técnico para operaciones petroleras, manufactureras e industriales por capacidad, responsabilidad y calidad de servicio.</p><p>La experiencia, la preparación del personal y la mejora de los equipos acompañan esta orientación.</p></article></div><div class="wide-photo">${img('patio-vapor-03.jpg')}</div>`)},
{name:'Valores y principios',html:screen(`${heading('Principios presentes<br>en cada intervención.','La seguridad, la coordinación y la responsabilidad forman parte de la manera de trabajar de SPS.')}<div class="values">${img('patio-vapor-02.jpg')}<div class="value-list">${values.map(([title,copy])=>`<article><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div></div>`)},
{name:'Equipo y forma de trabajo',html:screen(`${heading('Personal, equipos y<br>coordinación operativa.','SPS reúne experiencia técnica en vapor, instrumentación, automatización y manejo de hidrocarburos con equipos para la intervención en sitio.')}<div class="process">${[['Conocer el requerimiento','Compartir el servicio requerido, la ubicación, la urgencia y una descripción del trabajo.'],['Orientar la respuesta','Identificar la línea de servicio y los equipos relacionados con la necesidad operativa.'],['Trabajar en campo','Coordinar personal, equipos y actividades para la atención en la instalación.'],['Documentar la intervención','Conservar el registro fotográfico y la información técnica del trabajo realizado.']].map(([title,copy],i)=>`<article><span class="step">${i+1}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div><div class="process-photo">${img('hero-home-field.jpg')}</div>${link('Consultar los servicios de SPS','servicios')}`)}]},
{id:'servicios',name:'Servicios',sections:[
{name:'Catálogo general',html:screen(`${heading('Servicios petroleros<br>e industriales de SPS.','El catálogo reúne 22 prestaciones en tres líneas: vapor y recuperación, manejo y saneamiento, y automatización y control.')}<div id="service-explorer" class="service-explorer"></div>`)},
...groups.map((g,i)=>({name:g.name,html:screen(`${heading(g.title,g.intro,'catalog-head')}<nav class="category-links" aria-label="Categorías de servicios">${groups.map((other,j)=>`<a class="${i===j?'active':''}" href="${url('servicios',j+1)}">${other.name}</a>`).join('')}<a href="${url('servicios',4)}">Equipos y consulta</a></nav><div class="catalog">${img(g.image,g.caption)}<div class="catalog-list">${g.items.map((title,j)=>`<article><h3>${title}</h3><p>${serviceCopy[i][j]}</p></article>`).join('')}</div></div><div class="catalog-foot"><p>Describe el área, el fluido o equipo y la urgencia para orientar la consulta sobre este servicio.</p>${link('Consultar este servicio','contacto',1,'button')}</div>`)})),
{name:'Equipos, aplicaciones y consulta',html:screen(`${heading('Equipos y servicios<br>para necesidades de campo.','La selección del servicio parte de la instalación, el fluido y el tipo de trabajo. Comparte esa información al contactar con SPS.')}<div class="equipment-stage">${img('frac-tanks-modern-02.jpg','Equipos de almacenamiento temporal')}<div class="equipment-notes"><article><h3>Calderas y mantenimiento</h3><p>Alquiler de calderas portátiles, reparación y mantenimiento de calderas y calentadores para operaciones de vapor.</p></article><article><h3>Manejo y almacenamiento</h3><p>Trasegado con vacuum de 160 barriles, frac tanks de 500 barriles y bombeo de crudo.</p></article><article><h3>Control y soporte industrial</h3><p>PLC, RTU, SCADA, instrumentación, comunicaciones y energía para telemetría.</p></article>${link('Preparar una consulta técnica','contacto',1,'button')}</div></div>`)},
{name:'Información para solicitar servicio',html:screen(`${heading('Una consulta técnica<br>con la información necesaria.','El formulario de SPS permite describir la necesidad antes de continuar por los canales de contacto.')}<div class="process">${[['Servicio y aplicación','Indica si necesitas vapor, recuperación, saneamiento, almacenamiento, mantenimiento o automatización.'],['Ubicación del trabajo','Comparte el campo, la estación, el patio de tanques o la planta en la que se realizaría la intervención.'],['Fluido, equipo y alcance','Describe el área, el fluido o residuo, el equipo disponible y las actividades que requiere la operación.'],['Urgencia y contacto','Indica la prioridad y los datos de la persona con la que se puede conversar sobre el requerimiento.']].map(([title,copy],i)=>`<article><span class="step">${i+1}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div><div class="actions">${link('Completar datos del servicio','contacto',1,'button')}<a class="text-link" href="tel:+584146361373">Llamar a SPS ${arrow}</a></div>${footer()}`)}]},
{id:'proyectos',name:'Proyectos',sections:[
{name:'Portafolio completo',html:screen(`${heading('Trabajos y capacidad<br>documentados en campo.','Explora los seis registros del portafolio de SPS. Cada ficha incluye ubicación, descripción del trabajo y fotografías del proyecto.')}<div class="project-index">${projects.map(([file,title,location],i)=>`<a href="${url('proyectos',i+1)}">${img(file)}<h3>${title}</h3><p>${location}</p></a>`).join('')}</div>`)},
...projects.map(([file,title,location,description],i)=>({name:title,html:screen(`${heading(title)}<div class="project-detail"><div class="evidence"><figure><img id="evidence-image" src="/assets/sps-field/${file}" alt="${title}: fotografía principal"></figure><div class="evidence-tabs"><button type="button" data-evidence="${file}" data-caption="${title}: ${i===0?'antes de la intervención':'fotografía principal'}" aria-pressed="true">${i===0?'Antes de la intervención':'Fotografía principal'}</button><button type="button" data-evidence="${secondImages[i]}" data-caption="${title}: ${i===0?'después de la intervención':'segunda fotografía'}" aria-pressed="false">${i===0?'Después de la intervención':'Segunda fotografía'}</button></div></div><div class="project-copy"><div class="project-location">${location}</div><p>${description}</p><p>${projectDetails[i].copy}</p><h3>Trabajo documentado</h3><ul class="check-list">${projectDetails[i].scope.map(s=>`<li>${s}</li>`).join('')}</ul>${link('Consultar servicio relacionado','servicios',projectDetails[i].group)}</div></div><div class="project-foot"><p><strong>Línea de trabajo</strong><br>${projectDetails[i].service}</p><p><strong>Registro de campo</strong><br>Fotografías originales del portafolio de SPS.</p>${link('Hablar de una operación similar','contacto',1)}</div>`)}))]},
{id:'contacto',name:'Contacto',sections:[
{name:'Canales y ubicación',html:screen(`${heading('Contacto directo<br>con Service Petroleum and Supply.','Para servicios de vapor, saneamiento, tanques, mantenimiento, telemetría y automatización.')}<div class="contact-grid"><div class="contact-info"><p>Cuéntanos qué necesita tu operación. Puedes utilizar los teléfonos de contacto o preparar un resumen con el servicio requerido, la ubicación y la urgencia del trabajo.</p><a class="phone-link" href="tel:+582613226494">0261 322 6494</a><a class="phone-link" href="tel:+584146361373">+58 414 636 1373</a><address>Av. 5, Calle 13, N.º 26A-162<br>San Francisco, Maracaibo<br>Estado Zulia, Venezuela</address>${link('Completar datos del servicio','contacto',1,'button')}</div>${img('bajo-grande-caldera.jpg','Equipos SPS en campo')}</div>`)},
{name:'Formulario de servicio',html:screen(`${heading('Describe el trabajo<br>que requiere tu operación.','Campos que ayudan a orientar la conversación técnica con SPS.')}<div class="form-layout"><aside class="form-aside"><h3>Información de campo</h3><p>Indica el servicio y la ubicación. En la descripción puedes incluir el tipo de fluido, el área o el equipo involucrado, además de las actividades que necesitas realizar.</p><p>Al preparar la solicitud se descargará un resumen para compartirlo por tu canal de contacto. La información no se envía automáticamente.</p>${img('bajo-grande-patio-02.jpg')}</aside><form class="form" id="request-form"><label class="field">Nombre *<input name="Nombre" required autocomplete="name" placeholder="Nombre y apellido"></label><label class="field">Empresa<input name="Empresa" autocomplete="organization" placeholder="Nombre de la empresa"></label><label class="field">Teléfono<input name="Teléfono" autocomplete="tel" type="tel" placeholder="Número de contacto"></label><label class="field">Correo electrónico<input name="Correo" autocomplete="email" type="email" placeholder="Correo de contacto"></label><label class="field">Servicio requerido<select name="Servicio"><option value="">Seleccionar</option>${groups.map(g=>`<option>${g.name}</option>`).join('')}<option>Equipos de campo</option></select></label><label class="field">Ubicación del trabajo<input name="Ubicación" placeholder="Campo, estación o ciudad"></label><label class="field wide">Urgencia<select name="Urgencia"><option>Solicitar cotización</option><option>Atención inmediata</option><option>Programar visita técnica</option><option>Consulta general</option></select></label><label class="field wide">Descripción del trabajo *<textarea name="Descripción" rows="3" required placeholder="Área, fluido, equipo y actividades requeridas"></textarea></label><div class="form-bottom"><button class="button" type="submit">Preparar solicitud ${arrow}</button><p id="form-status" role="status">Se descargará un resumen. No se envía automáticamente.</p></div></form></div>`)},
{name:'Ayuda y datos de contacto',html:screen(`${heading('Antes de contactar<br>con el equipo de SPS.','Respuestas prácticas para preparar la información de tu solicitud.')}<div class="faq-layout"><div><h3>Una descripción clara del trabajo</h3><p style="margin-top:20px">La información del campo ayuda a identificar la línea de servicio y a explicar la necesidad de la operación. Si aún no sabes qué servicio corresponde, describe el problema o el área a intervenir.</p><div class="actions"><a class="button" href="tel:+584146361373">Llamar a SPS ${arrow}</a></div></div><div class="faq-list"><details open><summary>¿Qué información puedo incluir?</summary><p>Nombre, empresa, teléfono o correo, servicio, ubicación, urgencia y descripción del trabajo. Añade el fluido o equipo involucrado cuando lo conozcas.</p></details><details open><summary>¿Puedo describir varios servicios?</summary><p>Sí. Utiliza la descripción para indicar las actividades relacionadas con tu operación y señalar las que necesitas consultar.</p></details><details open><summary>¿Preparar el formulario envía la solicitud?</summary><p>No. Esta propuesta descarga un resumen. Para comunicarlo a SPS, continúa por los teléfonos de contacto publicados.</p></details></div></div>${footer()}`)}]}
]

export function explorerHtml(active=1){
 const g=groups[active]
 const images=['bajo-grande-caldera.jpg','frac-tanks-modern-01.jpg','bajo-grande-patio-04.jpg']
 const specs=[['Vapor en campo','Pozos, fosas y patios de tanques'],['Almacenamiento y trasegado','Frac tanks de 500 barriles · Vacuum de 160 barriles'],['Control de procesos','PLC · RTU · SCADA · Instrumentación']]
 return `<div class="service-rail"><div class="service-tabs" role="tablist" aria-label="Líneas de servicio">${['Vapor','Fluidos','Control'].map((name,i)=>`<button type="button" role="tab" aria-selected="${i===active}" data-category="${i}">${name}</button>`).join('')}</div><h3>Capacidad para resolver en campo.</h3><p>Consulta el alcance de cada línea y los servicios incluidos. Desde equipos de vapor hasta saneamiento, instrumentación y comunicaciones.</p></div><div class="service-visual" role="tabpanel" aria-label="${g.name}">${img(images[active])}<div class="service-caption"><div><h3>${g.title}</h3><p>${g.intro}</p>${link('Ver servicios de esta categoría','servicios',active+1)}</div><div class="facts"><p>${specs[active][0]}</p><strong>${specs[active][1]}</strong></div></div></div>`
}



